### ISSUE TITLE
The server responded with a non-JavaScript MIME type of "text/plain"

### ISSUE THREAD

**Issue by JeroLong** [naurril/SUSTechPOINTS#1]
win10环境 
错误：Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

ubuntu下没有错误

**Comment by naurril** [comment]
请问能够提供更详细的信息吗，我测试了一下Anaconda/python3/ Chrome79.0.3945.88,没问题。 用Edge有一些问题但是和您说的这个不一样
谢谢

**Comment by JeroLong** [comment]
> 请问能够提供更详细的信息吗，我测试了一下Anaconda/python3/ Chrome79.0.3945.88,没问题。 用Edge有一些问题但是和您说的这个不一样
> 谢谢

就是我运行后打开浏览器 左上角下拉不能选择案列数据 然后打开开发者模式调试  提示我上面说的错误  （因为win报错  我现在是在ubuntu二次开发）

**Comment by naurril** [comment]
好的,  那等有进一步信息的时候再说, 我也主要在ubuntu下开发的
