### ISSUE TITLE
How can i change or add label name ?

### ISSUE THREAD

**Issue by wyjforwjy** [naurril/SUSTechPOINTS#10]
Thanks for your great work . Could you tell me how to change or add a new label. I change the obj_cfg.js, but it did't work.

**Comment by naurril** [comment]
Yes, you only need to change obj_cfg.js, did you try to clean the cache and reload (or Ctrl+reload for chrome)?

**Comment by ouzhou** [comment]
How to label multiple tags？ like both <car> and <white color>

**Comment by wyjforwjy** [comment]
> Yes, you only need to change obj_cfg.js, did you try to clean the cache and reload (or Ctrl+reload for chrome)?

Thank you.
