### ISSUE TITLE
Custom Dataset Error

### ISSUE THREAD

**Issue by hoangduyloc** [naurril/SUSTechPOINTS#100]
[](url)Hello @naurril, thanks for your great work.
I have my own custom dataset (Only Lidar, No Camera), and I tried to label via your tool, everything looks good in SUS environment, but when convert label Json file to Txt KITTI file: 
- I only focus on these 7 variables for each class: Center (x,y,z); 3D dimensions (heigh, width, length); and Yaw angle.
- I saw a problem is the object center position was shifted. 
- I tried to test on KITTI dataset, it happends too.

So I do an simple exp: I used KITTI dataset (.bin - 0000099.bin); I converted it to (.pcd). After labeling, I converted the label to KITTI format, bellow is the result.

- The visualization in SUS env looks great
![KITTI_000099_SUSTech_Env](https://user-images.githubusercontent.com/38793688/191227806-5ff01bd4-be8e-4ed9-9ee2-99307ac4ef5b.png)

- The visulization in KITTI: Green is SUS label; Blue is KITTI groundtruth, it seem that the center location has been shifted
![SusTech_Label_IN_Green, KITTI_Label_In_Blue](https://user-images.githubusercontent.com/38793688/191227823-04860b61-7294-4d28-acb5-d42f87c75d64.png)

- So I wonder, if there is something cause that problem. Thank you.

**Comment by naurril** [comment]
Can you try to add a `-height/2` offset to z-axis of the position? in KITTI format the position is the bottom center of the box. see [here](https://github.com/naurril/SUSTechPOINTS/blob/522d1daef1e829f433cada6f420189ab3daee249/tools/trans_kitti_labels.py#L101) for reference. in this tool the position is the center of the box.

By the way this tool supports KITTI bin format

**Comment by hoangduyloc** [comment]
Hi @naurril, thanks for your fast response.

- In visualization I saw that the center was shifted not only the Z dimension, but also the X dimension. After adding the -height/2 to the Z dimension. The result looks like that.

- After adding height/2 to Z-axis, it still has the offset in X-axis
![Offset_Again](https://user-images.githubusercontent.com/38793688/191394717-25b8a974-f1fa-4478-91b5-4126ed4622fd.png)

- After adding height/2 to Z-axis; and a constant 0.3 meter to X-axis, the result looks resonable
https://drive.google.com/file/d/10N0FdXPWW0sbWUb4P4KoO4hGjZrmxj5_/view?usp=sharing 
![Uploading Add_0,3_Offset_to_X_axis.png…]()

- So I have the wonder again; how can we find the value ~~0.3 for X-axis?; In this equation, only Z-axis was changed  [here](https://github.com/naurril/SUSTechPOINTS/blob/522d1daef1e829f433cada6f420189ab3daee249/tools/trans_kitti_labels.py#L101). If you know how, it would be helpful for me. Thank you.

**Comment by naurril** [comment]
How did you convert the position? Is it like this `Tr_velo_cam * [x,y,z-h/2]^T`

**Comment by hoangduyloc** [comment]
Hi @naurril,
For each object in Json file; I convert it to KITTI format, like image bellow. My dataset has no Camera so there is no Tr_Velo_Cam matrix available.
![image](https://user-images.githubusercontent.com/38793688/191497296-6adb4770-b3e8-4b14-aa5b-c7c22a889a95.png)

I saw the Z, and X-axis were shifted; the Z-axis seem correct now; only X-axis still wrong.  Can you have a look at it? might be choose only random PC in KITTI dataset; and label it; then visualize the label again, you might see it more clearly. I'm curious too

**Comment by naurril** [comment]
visualize again with what tool？

**Comment by hoangduyloc** [comment]
Hi, @naurril  you can try this tool - https://github.com/kuixu/kitti_object_vis

**Comment by hoangduyloc** [comment]
![image](https://user-images.githubusercontent.com/38793688/191512563-9579fc17-f05e-4a1e-9399-9a1f192586c0.png)
I make the KITTI label like that; for the alpha angle, and 2D BBoxes I add the fake values

**Comment by naurril** [comment]
with this tool，how do you set the calib content?

**Comment by hoangduyloc** [comment]
I copy the fake calib file via KITTI to prevent the error; but I think you dont need the calib file for only Lidar visulization
![image](https://user-images.githubusercontent.com/38793688/191513454-f9ec1225-e19b-4ab7-b16f-ea51fb37299d.png)

**Comment by naurril** [comment]
In kitti format, the label is represented in the camera coordinate system, the visualization tool you are using surely does the camera(fake)->lidar coordinate system conversion.  if you use the fake calib, make use the Tr_velo_cam matrix is IDENTITY matrix

**Comment by hoangduyloc** [comment]
Hi @naurril,
I think I figure out the problem, and thank you for clarification. It was shifted 0.27m as their setup :D ~ 0.3m I found
![image](https://user-images.githubusercontent.com/38793688/191518738-2b0429fc-e0ae-4133-9555-310a08929c59.png)

**Comment by naurril** [comment]
This is what Tr_velo_cam does. you are hard coding this camera-lidar transform.

**Comment by hoangduyloc** [comment]
My bad; because I have my owndata set with VLP 16 Lidar, only Lidar information, no other information so I cant do anything. Then I tried to test KITTI dataset to see if it is wrong or not; also I didnt read clearly the center of your SUS tool is Lidar or Camera Coordinates, so that is ~~. Anyway, thanks for the help.
