### ISSUE TITLE
关于pretrained model file [deep_annotation_inference.h5]的问题 

### ISSUE THREAD

**Issue by Leozyc-waseda** [naurril/SUSTechPOINTS#101]
pretrained model file [deep_annotation_inference.h5](https://github.com/naurril/SUSTechPOINTS/releases/download/0.1/deep_annotation_inference.h5)

请问一下这个model是用的哪个3d object detction model？

我记得您说过，这个AI模型是fitting algorithm用来推算车的yaw角度的吧。

我仔细看了您的paper，里面并没有任何内容关于这个角度推算，可以详细讲解一下吗？

**Comment by naurril** [comment]
paper里没有，代码在这个帐号下，https://github.com/naurril/DeepAnnotate
