### ISSUE TITLE
将资料放置data 下面后，进行 使用 auto annotate 出现以下报错

### ISSUE THREAD

**Issue by Leo1993Java** [naurril/SUSTechPOINTS#104]
http://localhost:8081/auto_annotate?scene=example&frame=000950

出现
module algos.pre_annotate has no attribute annotate_file

跟踪代码之后，发现  algos/pre_annotate.py 下面 

if false 
   里面进行 def 定义

请教naurri ，这一块 提供 jpg，pcd之后，想要自动生成 标注json 具体是怎么使用？

**Comment by naurril** [comment]
代码里面的auto annotat功能效果没有调好， 不建议用
