### ISSUE TITLE
ply file format

### ISSUE THREAD

**Issue by ankhbayar479** [naurril/SUSTechPOINTS#107]
Thanks for your excellent work.
I have some ply files. Is it possible to annotate these files in SUS environment? If so, could you explain how? I am so new to this kind of work. I would appreciate if you explain it well. Thank you very much.

**Comment by naurril** [comment]
This tool supports only binary and PCD files. 
You can try to convert ply to pcd.  the [PCL](https://pointclouds.org/downloads/) library has a program named pcl_ply2pcd

**Comment by ankhbayar479** [comment]
@naurril 
Thank you so much for your reply. It worked like a charm.
