### ISSUE TITLE
Generate ID display

### ISSUE THREAD

**Issue by sayhiOK** [naurril/SUSTechPOINTS#108]
How is Generate ID used? Why is my ID not showing
![2022-11-11 23-25-22 的屏幕截图](https://user-images.githubusercontent.com/101408428/201371676-3d8004be-fb00-4724-9505-a3315a269fa7.png)

**Comment by sayhiOK** [comment]
> 如何使用生成 ID？为什么我的身份证没有显示 ![2022-11-11 23-25-22的屏幕截图](https://user-images.githubusercontent.com/101408428/201371676-3d8004be-fb00-4724-9505-a3315a269fa7.png)

@naurril Looking forward to your reply

**Comment by naurril** [comment]
When you create a box a new id is generated for you, or you could click the button to generate one.

**Comment by sayhiOK** [comment]
> When you create a box a new id is generated for you, or you could click the button to generate one.

@naurril Thank you very much for your reply. But I'm very sorry, I didn't find where the button to generate the ID is. My generated box is missing ID information. If possible, is there a demo

**Comment by naurril** [comment]
![Screenshot_2022-11-14-17-29-41-29_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/7512334/201624569-9eaa3465-64b9-4e1d-aea4-c15f73a3e044.jpg)

**Comment by sayhiOK** [comment]
> ![Screenshot_2022-11-14-17-29-41-29_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/7512334/201624569-9eaa3465-64b9-4e1d-aea4-c15f73a3e044.jpg)

@naurril I found that my interface seems to be different from yours
![2022-11-14 17-37-50 的屏幕截图](https://user-images.githubusercontent.com/101408428/201626754-2145e6fb-186d-4bbb-a274-95ba1b0e925a.png)

**Comment by naurril** [comment]
try default branch dev-auto-ann

**Comment by sayhiOK** [comment]
> try default branch dev-auto-ann

@naurril I found that I was using your previous version, which lacked the function of generating, I am very sorry, it has been solved now. Thanks again
