### ISSUE TITLE
interface

### ISSUE THREAD

**Issue by MayLkn** [naurril/SUSTechPOINTS#111]

**Comment by MayLkn** [comment]
Hello, can you tell me the code location of the three yellow circles on the homepage? I want to change the colo

**Comment by naurril** [comment]
[here](https://github.com/naurril/SUSTechPOINTS/blob/522d1daef1e829f433cada6f420189ab3daee249/public/js/editor.js#L306)

**Comment by MayLkn** [comment]
> Referen
Thank you. Thank you for your response

**Comment by MayLkn** [comment]
May I ask how to choose the code of this color

**Comment by naurril** [comment]
change the color value 0x888800

```
 var box = new THREE.LineSegments( bbox, 
            new THREE.LineBasicMaterial( { color: 0x888800, linewidth: 1, opacity: 0.5, transparent: true } ) );    
```

**Comment by MayLkn** [comment]
> change the color value 0x888800
> 
> ```
>  var box = new THREE.LineSegments( bbox, 
>             new THREE.LineBasicMaterial( { color: 0x888800, linewidth: 1, opacity: 0.5, transparent: true } ) );    
> ```
Thank you. Thank you for your response
