### ISSUE TITLE
关于anno_transform中跟踪和自动旋转算法

### ISSUE THREAD

**Issue by GatsbyChen** [naurril/SUSTechPOINTS#113]
您好，想请教一下，为什么用跟踪和自动旋转算法替换了icp呢，是前者的效果更好一些吗？
icp能感知点云的形态，在相邻帧transform的过程中是不是能更精确一下呢？
希望您能给我一些启发，非常感谢！
https://github.com/naurril/SUSTechPOINTS/issues/12

**Comment by GatsbyChen** [comment]
我看到master分支上保留了go_icp的部分，但是~/code路径下的代码是没有的，请问可以分享一下吗，想验证一下和现在版本的区别和效果

**Comment by naurril** [comment]
icp用起来有误差累计的问题

**Comment by naurril** [comment]
> 我看到master分支上保留了go_icp的部分，但是~/code路径下的代码是没有的，请问可以分享一下吗，想验证一下和现在版本的区别和效果

https://github.com/yangjiaolong/Go-ICP

**Comment by GatsbyChen** [comment]
> icp用起来有误差累计的问题

是这样的，如果连续帧人都不干涉的话，确实是会误差累计；我们现在设想的场景是，人标注一帧后，算法帮助把当前帧的结果transform到下一帧，transform的结果如果不是很贴别或者存在朝向偏差的情况下，人需要微调一下；接着再重复transform的操作到下一帧，这样是不是就能提升一定的标注效率并且解决累计误差的问题；

**Comment by GatsbyChen** [comment]
> icp用起来有误差累计的问题

感谢您的回复，再您请教一下，连续帧tracking是不是也存在累计误差的问题呢，您那边的实验结果是 跟踪和自动旋转算法 比 icp 效果更好是吗？

**Comment by GatsbyChen** [comment]
> > 我看到master分支上保留了go_icp的部分，但是~/code路径下的代码是没有的，请问可以分享一下吗，想验证一下和现在版本的区别和效果
> 
> https://github.com/yangjiaolong/Go-ICP

感谢，太赞了

**Comment by GatsbyChen** [comment]
请问可以加一下您微信或者邮箱沟通交流一下吗，感谢

**Comment by naurril** [comment]
可以啊，可以发邮件

**Comment by GatsbyChen** [comment]
> 可以啊，可以发邮件

好呀，可以给我发一下您的邮箱地址吗

**Comment by GatsbyChen** [comment]
> > 可以啊，可以发邮件
> 
> 好呀，可以给我发一下您的邮箱地址吗

是这个吗？naurril@gmail.com

**Comment by naurril** [comment]
> > > 可以啊，可以发邮件
> > 
> > 
> > 好呀，可以给我发一下您的邮箱地址吗
> 
> 是这个吗？[naurril@gmail.com](mailto:naurril@gmail.com)

是的
