### ISSUE TITLE
标注类别能否增添

### ISSUE THREAD

**Issue by hehualin-tut** [naurril/SUSTechPOINTS#116]
首先感谢您的开源工作，我想问下能否根据自己的需求来改变或增添标注类别，如果能的话该怎么实现呢？

**Comment by naurril** [comment]
修改obj_cfg.js

**Comment by hehualin-tut** [comment]
@naurril  感谢，我再问下，最后生成的label转换成kitti的格式是用到了[trans_kitti_labels.py](https://github.com/naurril/SUSTechPOINTS/blob/dev-auto-annotate/tools/trans_kitti_labels.py)吗？还有一点就是使用图像辅助标注时，内外参矩阵是如何使用的，因为我看到一个是4*4，一个是3*3,那激光雷达点是4*1吗？感觉缺少了一些东西，是需要补全吗？KITTI格式的calib该如何转化成这样的形式呢？

**Comment by zheyuanWang** [comment]
我把obj_cfg.js里的obj_type_map删成空字典之后还是能正常显示; 

在里面修改颜色后重启main.py和浏览器页面, 颜色改动未生效; 

所以改了之后需要再编译安装一下之类的操作么?

**Comment by hehualin-tut** [comment]
> 我把obj_cfg.js里的obj_type_map删成空字典之后还是能正常显示;
> 
> 在里面修改颜色后重启main.py和浏览器页面, 颜色改动未生效;
> 
> 所以改了之后需要再编译安装一下之类的操作么?

@zheyuanWang 

你可以试试清除一下浏览器缓存。

**Comment by zheyuanWang** [comment]
清除缓存之后启动程序, F12查看source发现代码还是没有被修改

我现在的做法是把obj_cfg.js改名成xx.js 再改名回来, 期间配合清理缓存和和重启程序, 总体有点玄学瞎调

hualin he ***@***.***> 于2023年2月15日周三 13:44写道：
