### ISSUE TITLE
标注的bbox的俯仰角问题

### ISSUE THREAD

**Issue by hehualin-tut** [naurril/SUSTechPOINTS#117]
我发现有些标注车辆如果在采集车附近，没有地面线作为参考的话，bbox不能很好的与地面重合，然后我发现也调整不了俯仰角只能旋转，导致前后几个Frame的bbox z值差距很大，例如id1002 car 的4帧中，Z值波动从0.7增大到1.1，不知道能否调整Bbox的俯仰角。感谢

**Comment by naurril** [comment]
在左侧几个投影视图中调，或者在3d界面转z轴的时候按z/x/c打开其他轴的旋转。
9个自由度都可以调。

**Comment by hehualin-tut** [comment]
感谢
