### ISSUE TITLE
缺失文件

### ISSUE THREAD

**Issue by KevinDuBl** [naurril/SUSTechPOINTS#12]
程序中用命令行调用了~/code/pcltest/build/extract_object和~/code/go_icp_pcl/build/test_go_icp两个文件，但是这两个文件根本没放出来啊，请问最近会更新吗？

**Comment by naurril** [comment]
这个功能已经用新方案替代了，这俩个文件后面不需要了。你试试checkout batch-edit的分支。

**Comment by KevinDuBl** [comment]
感谢！这里的rotation.predict中的deep_annotation网络只有推理部分，请问网络结构和训练部分是非开源的吗?

**Comment by naurril** [comment]
是开源的，https://github.com/naurril/DeepAnnotate

**Comment by KevinDuBl** [comment]
非常感谢，很好的标注工具。那请问最终的程序中是不是没有调用rotation.py和trajectory.py中的算法，其中的deep_annotation网络是不是也没用到呢？如果用到了，这个网络是做什么用呢？

**Comment by naurril** [comment]
deep_annotation用来自动推导目标的旋转角度的(yaw).　deep_annotation训练的模型，在rotation.py里面用的．　trajectory.py目前是没有用到．

**Comment by KevinDuBl** [comment]
trajectory.py目前没有用到的话，那连续帧的标注迁移目前就没有实现吗？就是跟踪加上GO-ICP匹配功能，没有实现吗？

**Comment by naurril** [comment]
开始是在后端trajectory.py,  现在放到前端实现的．
go-icp是早期的版本用的方案，现在版本没有用了．

**Comment by KevinDuBl** [comment]
那请问现在用的什么方法啊，有论文吗？

**Comment by KevinDuBl** [comment]
可以告诉我现在用的跟踪和自动旋转算法在哪个文件里吗？我看了好久都没有找到，谢谢！

**Comment by naurril** [comment]
跟踪是简单的线性插值，入口在这里
https://github.com/naurril/SUSTechPOINTS/blob/batch-edit/public/js/box_editor.js
372行．

自动旋转是用的神经网络计算的角度，在后端做的，前端的代码在ml.js,  predict_rotation

可能代码有点不容易看 :)

**Comment by KevinDuBl** [comment]
谢谢！非常感谢！

**Comment by KevinDuBl** [comment]
你好，我看见auto_totate_y中有一步求旋转角的方法是theta =  Math.atan2(dotproduct(x,z), dotproduct(x,x))，请问这个Math.atan2(dotproduct(x,z), dotproduct(x,x))方法的物理意义是什么？是经验公式还是由数学推导而来？

**Comment by naurril** [comment]
以车为例，这个算法是假设车前后一小片地方是平的（和车在同一个水平面上，对马路上的车大多数是满足的），利用这些点计算一个旋转角度，让前后的点和x轴平行。其实就是求这些点的斜率。 车的坐标是向前为x，左手边为y，向上为z。

把这些点投射到x-z平面上，就等价于拟合一条直线， 这就变成了线性回归问题，z=wx，w为参数，最小化|z-wx|^2, 对w求导，可得 w=<z,x>/<x,x>，就是上面的代码。

**Comment by alanwanga** [comment]
Hi @naurril, does the pre-trained model for yaw prediction also work for other dataset? (e.g. KITTI, Waymo, nuScenes) Or we still have to finetune the weights?

Thanks,

**Comment by naurril** [comment]
> Hi @naurril, does the pre-trained model for yaw prediction also work for other datasets? (e.g. KITTI, Waymo, nuScenes) Or we still have to fine-tune the weights?
> 
> Thanks,
Hi,  It works for KITTI and nuScenes.  It should also work for Waymo but I haven't tested it.
