### ISSUE TITLE
about perceptual model

### ISSUE THREAD

**Issue by Ehangiun** [naurril/SUSTechPOINTS#120]
Thank you for your busy schedule to answer my doubts!
Your tools are very helpful to us in using them,,when using the tool, I want to replace the model used for perception and have a few questions for you.
1.Does this awareness model have a git address?
2.Why is 'pred_cls[0]*3+1.5' used when yaw Angle output by model? Why is 'pred_cls[0] 'used?
3.What does the shape of '(10,120)' correspond to in terms of the actual output?

**Comment by naurril** [comment]
1 mode [code](https://github.com/naurril/DeepAnnotate)
2 it's a 120-class classification algorithm for yaw angle.

**Comment by Ehangiun** [comment]
Thanks
