### ISSUE TITLE
请问各位大佬 现在有标注点云后再常驻射角里边出现对应的2D矩形的功能吗  

### ISSUE THREAD

**Issue by zhou1591** [naurril/SUSTechPOINTS#138]
先给各位浏览问题的大佬问好

请问各位大佬 现在又标注点云后再常驻射角里边出现对应的2D矩形的功能吗  

或者说常驻视角里边现在的2D 标注有什么用处呢 并没有看到和点云有联动的效果

**Comment by naurril** [comment]
可以一定程度上联动，也可以单独标矩形框。

**Comment by zhou1591** [comment]
大佬我可以问下 怎么联动的嘛  我在点云上边标注了3d矩形后    射角上并不会出现对应的2d框  出现的也是3d矩形框


然后我单独在射角上标注2d矩形  也不会反应在点云上

**Comment by zhou1591** [comment]
> 可以一定程度上联动，也可以单一标记形状框。

大佬我可以问下 怎么联动的嘛 我在点云上边标注了3d矩形后 射角上并不会出现对应的2d框 出现的也是3d矩形框

然后我单独在射角上标注2d矩形 也不会反应在点云上

**Comment by zhou1591** [comment]
> 可以一定程度上联，也可以单一标记形状状态框。

谢谢大佬  期待你的回复

**Comment by naurril** [comment]
就是可以互相选择，可以根据3d框生成2d框，不能反过来

**Comment by zhou1591** [comment]
> 就是可以互相选择，可以根据3d框生成2d框，不能反过来

大佬 可以给我邮箱发一个邮件吗 有问题想请教下  1402663440@qq.com
