### ISSUE TITLE
Visualisation failed

### ISSUE THREAD

**Issue by Jayden9912** [naurril/SUSTechPOINTS#159]
Hi.

I have converted radar point into pcd file and successfully visualize the points. However, when I zoom out to a certain extent, the whole visualization become blank.

Could you advice me on this issue?

**Comment by Jayden9912** [comment]
My radar point can be up to 1800m from the origin

**Comment by naurril** [comment]
What is the range of the radar point?

**Comment by Jayden9912** [comment]
Thanks for the reply.

The range of the radar point can be up to 2000m

**Comment by naurril** [comment]
It's too large， a few parameters need to be adjusted, please provide the
value range for each  dimension （ x，y，z）

**Comment by Jayden9912** [comment]
Thanks for the speedy reply.

x and y values can be up to 2000m while the range for z doesn't matter since it's a 2D radar.

**Comment by naurril** [comment]
increase the last parameter when creating main camera  [here](https://github.com/naurril/SUSTechPOINTS/blob/522d1daef1e829f433cada6f420189ab3daee249/public/js/view.js#L75), maybe 10000 is ok in your case

**Comment by Jayden9912** [comment]
it works, thanks
