### ISSUE TITLE
 automatic yaw angle (z-axis) prediction

### ISSUE THREAD

**Issue by hefc2016** [naurril/SUSTechPOINTS#16]
hello,

thank you for sharing the wonderful project!

I have clone the repo and try from my side, it works good.  But I can't find the feature 'automatic yaw angle (z-axis) prediction' which you mentioned in read me.

When I want to add a 3D bbox, I click the right mouse and select the new, then a 3D bbox is created and I can't choose rectangle area to create 3D bbox. could you please share more detail how to operate and automatic yaw angle (z-axis) prediction like the gif picture showed in readme?

thanks.

**Comment by naurril** [comment]
Hi, It's not an independent feature, when you create a new box by right-clicking or drawing a rectangle (ctrl + mouse left key drag), the box will be auto-rotated to fit the object.

**Comment by hefc2016** [comment]
Hi,

thanks for your help. 

I go through the readme again that I found this operation has been descripted in readme. 

I will try again.
