### ISSUE TITLE
about calib file

### ISSUE THREAD

**Issue by xiaoxiaojiea** [naurril/SUSTechPOINTS#166]
hello, first, thanks to your greate project!

then, i have a question about calib file format. i have a calib file like kitti format, it is :(i only use one camera and lidar, P2 is c、camera internal matrix, Tr is lidar to camera matrix)

`P2: 1.0218747818451506e+03 0.000000000000e+00 9.7595332072576900e+02 0.000000000000e+00 0.000000000000e+00 1.0216544134998642e+03 5.4054806903113194e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00`

`Tr: -8.7733885104888110e-03 -9.9970331512471100e-01 -2.2722442269848264e-02 2.1409160713165266e-02 -2.5927911839857026e-01 2.4220430390878178e-02 -9.6549868436686170e-01 1.8610451102434678e-03 9.6576258284140626e-01 -2.5792402647277779e-03 -2.5941468945137336e-01 4.1976232497305740e-02`

i make sure the P2 and Tr is valid in my robot, thus i want to know how can i translate P2 and Tr to the front.json which this project used.

note that, i have try some method to use P2 and Tr, but they all failed, which can't show the bbox in image, they are:
1, i make P2 is intrinsic, and i make Tr is extrinsic, failed.
2, i make P2 is intrinsic, and i make Tr' inverse operation as extrinsic, failed.

Looking forward to your reply.

**Comment by xiaoxiaojiea** [comment]
i have sovle this problem, thank you!

**Comment by mohamedsamirx** [comment]
Can you provide the answer
