### ISSUE TITLE
Saving the bbox after pasting the bbox

### ISSUE THREAD

**Issue by Jayden9912** [naurril/SUSTechPOINTS#182]
Hi. Naurril.

May I know how should I save the world after pasting the bounding box?
https://github.com/naurril/SUSTechPOINTS/blob/1b2769ead41a3bcec1b1d0811da5d1c8b4f5f5d8/src/editor/js/editor.js#L575-L586

I have commented out L579 - L583 to avoid the error from popping out when there is no point in the bounding box. However, the box is not being saved automatically. How should I call the function in save.js to save the world (all the bounding boxes)?

**Comment by naurril** [comment]
this is a bug, could you try adding an 'else' branch and call `this.onBoxChanged(box)`,  

reference code, `setModified` is used to save automatically:
[code](https://github.com/naurril/SUSTechPOINTS/blob/1b2769ead41a3bcec1b1d0811da5d1c8b4f5f5d8/src/editor/js/editor.js#L2467C5-L2467C63)

**Comment by Jayden9912** [comment]
I see, thank you!
