### ISSUE TITLE
Camera calib for NuScenes data

### ISSUE THREAD

**Issue by Ruhail-Ali-Khan** [naurril/SUSTechPOINTS#183]
NuScene has camera extrinsic values in form of translation 3x1 and rotation 4x1 but SusTech tool required rotation matrix. I converted rotation and translation into rotation matrix but still labels in image is not perfect. What is the reason and how to solve it.

**Comment by naurril** [comment]
Please check the code below for reference

https://github.com/naurril/SUSTechPOINTS/blob/1b2769ead41a3bcec1b1d0811da5d1c8b4f5f5d8/tools/import-nuscenes.py#L64
