### ISSUE TITLE
Working of auto annotate function 

### ISSUE THREAD

**Issue by Ruhail-Ali-Khan** [naurril/SUSTechPOINTS#184]
I want to know the working of auto annotate function how it is tracking the object in all frames. According to your paper you are using registration algorithm(go-icp maybe). Where i can find the calculation of position of the object in SusTech points. Thanks

**Comment by naurril** [comment]
registration was used for initial version and now it has been changed to a simple tracking [alg](https://github.com/naurril/SUSTechPOINTS/blob/522d1daef1e829f433cada6f420189ab3daee249/public/js/ml.js#L524)
