### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by Jayden9912** [naurril/SUSTechPOINTS#190]
Hi.

Could you shed some light on how to use the authentication mechanism? I changed auth to yes in auth.conf but I encountered this error:
```
python3.8/site-packages/cheroot/ssl/builtin.py", line 219, in __init__
    self.context.load_cert_chain(certificate, private_key)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by Jayden9912** [comment]
Follow up question: I am using fusion branch, is it possible if I just use python3 main.py instead of launching main.py + npm run start. From my experiment, there is no difference in these 2 approaches.

**Comment by naurril** [comment]
> Follow up question: I am using fusion branch, is it possible if I just use python3 main.py instead of launching main.py + npm run start. From my experiment, there is no difference in these 2 approaches.

`npm run start` is for front-end debugging.

**Comment by naurril** [comment]
> Hi.
> 
> Could you shed some light on how to use the authentication mechanism? I changed auth to yes in auth.conf but I encountered this error:
> 
> ```
> python3.8/site-packages/cheroot/ssl/builtin.py", line 219, in __init__
>     self.context.load_cert_chain(certificate, private_key)
> FileNotFoundError: [Errno 2] No such file or directory
> ```

you need to [create certification keys](https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/) to enable `https`, 
but a better way is to use network proxy (e.g. nginx)

**Comment by Jayden9912** [comment]
> > Follow up question: I am using fusion branch, is it possible if I just use python3 main.py instead of launching main.py + npm run start. From my experiment, there is no difference in these 2 approaches.
> 
> `npm run start` is for front-end debugging.

So actually I can just deploy nginx to direct the request to the cherrypy http server right?

**Comment by naurril** [comment]
yes

**Comment by Jayden9912** [comment]
Thanks.
