### ISSUE TITLE
PCD Frames are not in order

### ISSUE THREAD

**Issue by ainayves** [naurril/SUSTechPOINTS#208]
Hello , I have those frames in my lidar directory , and they are not in order in the SUSTech dropdown : 

<img width="293" alt="image" src="https://github.com/naurril/SUSTechPOINTS/assets/66997516/a2d4b3d3-c917-46f9-a14a-c5ec922624e5">

What is the reason about this ? 

Thank you in advance.

It is a great tool by the way :)

**Comment by naurril** [comment]
It uses the `string` order, same as when you sort files in your computer
you need to name the files  as 000-xxx, 001-xxx, 002-xxx, ..., 100-xxx, ...

**Comment by ainayves** [comment]
Thank you very much , I will do that then.
