### ISSUE TITLE
你好，这个项目有论文吗？能不能被引用呢?

### ISSUE THREAD

**Issue by liminghui520** [naurril/SUSTechPOINTS#21]

**Comment by naurril** [comment]
你好，请用下面这个，谢谢！

@inproceedings{li2020sustechpoints,
  title={SUSTech POINTS: A Portable 3D Point Cloud Interactive Annotation Platform System},
  author={E Li and Shuaijun Wang and Chengyang Li and Dachuan Li and Xiangbin Wu and Qi Hao},
  booktitle={2020 IEEE Intelligent Vehicles Symposium (IV)},
  pages={837--844},
  year={2020},
  organization={IEEE}
}

**Comment by liminghui520** [comment]
谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naurril/SUSTechPOINTS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月14日(星期六) 下午4:17
收件人:&nbsp;"naurril/SUSTechPOINTS"<SUSTechPOINTS@noreply.github.com&gt;;
抄送:&nbsp;"黎明慧"<1448964728@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [naurril/SUSTechPOINTS] 你好，这个项目有论文吗？能不能被引用呢? (#21)





 
你好，请用下面这个，谢谢！
 
@inproceedings{li2020sustechpoints,
 title={SUSTech POINTS: A Portable 3D Point Cloud Interactive Annotation Platform System},
 author={E Li and Shuaijun Wang and Chengyang Li and Dachuan Li and Xiangbin Wu and Qi Hao},
 booktitle={2020 IEEE Intelligent Vehicles Symposium (IV)},
 pages={837--844},
 year={2020},
 organization={IEEE}
 }
