### ISSUE TITLE
Error after npm start in fusion branch

### ISSUE THREAD

**Issue by mohamedsamirx** [naurril/SUSTechPOINTS#214]
![image](https://github.com/user-attachments/assets/4456be32-47ac-4298-931f-93ed9f828852)
got this error every time I run npm start.
![image](https://github.com/user-attachments/assets/7ccce64c-2509-41ff-a4ce-bcb75ba4c260)

**Comment by naurril** [comment]
did you start the server `main.py`

**Comment by mohamedsamirx** [comment]
Yes, it is running 
Also, this appears before the error above.
![image](https://github.com/user-attachments/assets/d300f32a-6593-40c4-b2a4-2f41074df308)
![image](https://github.com/user-attachments/assets/9e2a0303-9059-449d-a07c-242845aead04)

**Comment by naurril** [comment]
please change the proxy setting in package config from https to http

**Comment by mohamedsamirx** [comment]
Okay, it runs, but what does the front end provide more ? Sorry for too many questions, but i am trying to learn more .

**Comment by naurril** [comment]
`npm run start` is for front end debugging

**Comment by mohamedsamirx** [comment]
Okay thank you
