### ISSUE TITLE
不能保存

### ISSUE THREAD

**Issue by JunjieWang0528** [naurril/SUSTechPOINTS#216]
更改了obj_cfg.js文件
改变一个标注类别名称，清除浏览器缓存后就不能保存
报错提示如下：
save failed, status : 500

**Comment by JunjieWang0528** [comment]
已经解决了。是因为没有切换到root所以不能保存

**Comment by jmjkx** [comment]
> 已经解决了。是因为没有切换到root所以不能保存

我用的 docker ， 默认就是 root 呀， 很奇怪。

**Comment by yaobaishen** [comment]
同样的问题，我用root运行的main.py, 也不能保存

**Comment by yaobaishen** [comment]
找到原因了，除了要用root user, 还需要手动创建label文件夹
