### ISSUE TITLE
Clarification about the yaw prediction

### ISSUE THREAD

**Issue by mohamedsamirx** [naurril/SUSTechPOINTS#217]
If I want to use the yaw prediction in an annotation tool like sustech which function does the method rely on ? Other than the prediction code in the pre_annotate file, I am asking about the JavaScript code like the grow_box and this method ?

**Comment by naurril** [comment]
the code is in ml.js, `predictRotation`

**Comment by mohamedsamirx** [comment]
Thanks for your amazing tool i have already solve it, thank you again
