### ISSUE TITLE
代码中存在未处理合并

### ISSUE THREAD

**Issue by xsy199** [naurril/SUSTechPOINTS#22]
hello，naurril
     你的 batch-edit 分支代码中 algos/pre_annotate.py 存在冲突，不知你是否有时间解决一下？

**Comment by naurril** [comment]
已修改，谢谢提醒

**Comment by xsy199** [comment]
恩恩，还有另一个问题，就是我在使用的时候，点云的三维坐标轴只能在第一次加载的时候正确显示，但是在选择新的一帧时，三维坐标轴就会显示异常，不出现在点云的中间，请问这个问题你有遇到过吗？

**Comment by naurril** [comment]
这是代码没写好:(，为了加载多帧，每次加载新点云的时候整体平移了位置，这些新位置上面没有画坐标轴

后面我再修改一下这个问题． 谢谢

**Comment by naurril** [comment]
已修改，请更新，谢谢

**Comment by xsy199** [comment]
抱歉，我更新后并没有看到坐标轴的问题得到修改？

**Comment by naurril** [comment]
清空一下缓存试试，或者Ctrl+刷新
