### ISSUE TITLE
每次点ctrl+s保存的时候，服务端会疯狂打印log。

### ISSUE THREAD

**Issue by heyu3913** [naurril/SUSTechPOINTS#222]
每次点ctrl+s保存的时候，服务端会疯狂打印log。如果我文件夹里面有5000张pcd，服务器的log要刷十几分钟。看了是checkscene接口耗时四五秒才能请求到数据。 请问下这个checkscene有作用吗？我看了代码，这个checkscene每次都要遍历所有文件夹的json，这个操作非常耗时。一次操作要卡好几秒，如果多人使用网站就直接打不开了。

**Comment by naurril** [comment]
这是做一致性检查,可以把代码去掉

**Comment by heyu3913** [comment]
好的 谢谢解答。我注释掉了确实不卡了。麻烦大佬看下220这个issue[文件夹下面的pcd文件过多，大概有5000多张，连续加载到第200张左右浏览器就崩溃了](https://github.com/naurril/SUSTechPOINTS/issues/220),我关闭预加载，自动以10hz速度播放浏览器不会内存泄漏。但是我手动按4播放下一帧，浏览器内存会不停增加直到内存泄漏。请问这是啥原因呢，我仔细看了代码。发现手动触发下一帧也是会销毁上一帧的。为什么自动播放内存不会泄露，手动一直按下去播放就会内存泄漏呢？？
