### ISSUE TITLE
Batch_edit can't load predict model, nothing shows on browser

### ISSUE THREAD

**Issue by wolflion521** [naurril/SUSTechPOINTS#23]

**Comment by wolflion521** [comment]
Batch_edit can't load predict model, and even when I give up predict function, nothing shows on browser. So should I choose a certain commit?
Thanks for your work.

**Comment by naurril** [comment]
I have removed the test code which needs pre-trained models. please try again, thank you!

**Comment by wolflion521** [comment]
@naurril Thanks a lot for this awsome work.   Best one I have ever tried.
