### ISSUE TITLE
How to add another PCDLoader?

### ISSUE THREAD

**Issue by wolflion521** [naurril/SUSTechPOINTS#27]
Hi, 
I get some lidar data, which are stored in binary, but not in kitti style. Actually they are stored in nuscenes style. So I want to change the PCDLodar.js snippet below.  
for ( var row = 0; row < data.byteLength/(4*4); row += 1 ) {
			position.push( dataview.getFloat32( row*16 + 0, this.littleEndian ) );
			position.push( dataview.getFloat32( row*16 + 4, this.littleEndian ) );
			position.push( dataview.getFloat32( row*16 + 8, this.littleEndian ) );
		}
I hope to change to 4*5 and row * 20. But when I change these digits in the js file,and python main.py to start the webpage, I found they don't update in my browser console. Can you tell me how to change them please? I have never use js before.  
Thanks a lot.

**Comment by naurril** [comment]
Maybe you need to clean the browser cache, just hold Ctrl when you click 'reload' or press F5.

**Comment by wolflion521** [comment]
Thanks, that doesn't work. May it is only a small problem, I think I need to learn some js knowledge to solve that. Thanks a lot.
