### ISSUE TITLE
我这边基于此做了一个数据库后端,

### ISSUE THREAD

**Issue by HaomingJu** [naurril/SUSTechPOINTS#28]
有没有兴趣继续 前后端结合 继续开发?

**Comment by naurril** [comment]
好啊，请问你的数据库后端大致实现了什么功能？

**Comment by HaomingJu** [comment]
多用户的 任务分发/管理  进度查询等 并配有前端

**Comment by naurril** [comment]
方便留个email吗？ 我们邮件交流一下，谢谢

**Comment by HaomingJu** [comment]
juhaoming@126.com

**Comment by hwx628** [comment]
你好 ，请问开发的怎么样了，前后端+任务管理，  是类似cvat那种前后端， 然后准备封在docker里边么？  我这边也想要做这个开发，请问你们到什么进度了

> [juhaoming@126.com](mailto:juhaoming@126.com)
