### ISSUE TITLE
how to transform output json files to txt with kitti format

### ISSUE THREAD

**Issue by TianchaoHuo** [naurril/SUSTechPOINTS#30]
Thanks for your great job at fist. Right now I have labeled data and obtained output label files. could you provide us scripts or tell us how to transform these label files to txt files with kitti format! Thanks .

**Comment by Vova-B** [comment]
@TianchaoHuo Hi! Were you able to slove the problem of converting data to kitti format?

**Comment by AgapeGithub** [comment]
did you guy solve it?
