### ISSUE TITLE
How can I change or add another class name?

### ISSUE THREAD

**Issue by sangjun7997** [naurril/SUSTechPOINTS#35]
I want to add new class (ex. tree, train, Scooter ...)
So I want to know how can I change or add class name to platform.

**Comment by naurril** [comment]
Edit obj_cfg.js

**Comment by sangjun7997** [comment]
I edited obj_cfg.js file, but platform was not changed. Is there anything to do for applying the changes to platform?

**Comment by naurril** [comment]
Ctrl+reload, or clean cache
