### ISSUE TITLE
3d点云图框转2d图片图框 位置不正确

### ISSUE THREAD

**Issue by missing64001** [naurril/SUSTechPOINTS#38]

**Comment by missing64001** [comment]
%YAML:1.0
---
CameraExtrinsicMat: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 8.0161552836363503e-02, 4.7980668465075427e-02, 9.9562642637713639e-01, 1.5285094972460525e+00,
       -9.9620144102008923e-01, 3.7938603409721328e-02, 7.8379533558306458e-02, -5.3043462933157803e-01,
       -3.4011973720452005e-02, -9.9812750579520881e-01, 5.0839628427781447e-02, -5.9513324248828947e-01,
        0., 0., 0., 1. ]
%YAML:1.0
---
model_type: PINHOLE
camera_name: frontWindow3
image_width: 1920
image_height: 1080
distortion_parameters:
   k1: -1.2562960883964325e+00
   k2: 3.5311551842254183e-01
   p1: 5.2159978822362736e-03
   p2: 1.9736695302629018e-02
projection_parameters:
   fx: 3.7903484311224056e+03
   fy: 3.7663196304645676e+03
   cx: 1.0354884836336173e+03
   cy: 3.3674759246588224e+02

以上是我的相机内外参设置
下面是calib的json设置 但显示图框不正确 请问应该怎么设置呢


{
    "extrinsic": [ 8.0161552836363503e-02, 4.7980668465075427e-02, 9.9562642637713639e-01, 1.5285094972460525e+00,
       -9.9620144102008923e-01, 3.7938603409721328e-02, 7.8379533558306458e-02, -5.3043462933157803e-01,
       -3.4011973720452005e-02, -9.9812750579520881e-01, 5.0839628427781447e-02, -5.9513324248828947e-01,
        0, 0, 0, 1 ],
    "intrinsic": [3.7903484311224056e+03, 0.0, 1.0354884836336173e+03, 
                0.0,3.7663196304645676e+03, 3.3674759246588224e+02, 
                0.0, 0.0, 1.0]
}

**Comment by missing64001** [comment]
%YAML:1.0
---
model_type: MEI
camera_name: sur_front
image_width: 1920
image_height: 1080
mirror_parameters:
   xi: 1.7569851477153153e+00
distortion_parameters:
   k1: 2.9932081670583016e-01
   k2: -2.4432099336464344e-01
   p1: 1.6237070444522692e-03
   p2: 2.0912606026379668e-04
projection_parameters:
   gamma1: 1.3185388450105215e+03
   gamma2: 1.3281422914424445e+03
   u0: 9.6187899139060880e+02
   v0: 5.6281018293926525e+02

还有 这种相机怎么进行转换呢

**Comment by naurril** [comment]
你确定矩阵没有问题吗, 关系是这样的, 你看看对不对: 内参 * 外参 * 点云点 = 图像点

**Comment by missing64001** [comment]
好的,谢谢,我去确认一下数据的正确性

**Comment by zhou1591** [comment]
@naurril @missing64001   大佬 你们解决了吗  这个内参是怎么转换成矩阵的啊
