### ISSUE TITLE
请问一下采用的具体的3D预测算法文档有吗？

### ISSUE THREAD

**Issue by witcjt** [naurril/SUSTechPOINTS#45]
我想在我的论文中引用本项目，想知道模型的网络架构复现一下训练我自己的数据集，请问有相关文档论文吗？谢谢

**Comment by naurril** [comment]
你好，目前这个项目里面只有一个方向判定算法是神经网络的，代码在https://github.com/naurril/DeepAnnotate，我不知道你说的是不是这个

**Comment by witcjt** [comment]
好的，我学习一下
