### ISSUE TITLE
最新的dev分支没有看到上一个，下一个，播放功能

### ISSUE THREAD

**Issue by HaKLMTT** [naurril/SUSTechPOINTS#47]
您好，您的项目有3个分支，请问哪个分支是最新最全的分支，我研究的是dev分支，发现没有找到原来的上一个，下一个和播放的功能。麻烦您帮忙回复下，谢谢！

**Comment by naurril** [comment]
默认分支就是最新的分支　dev-auto-annotate

**Comment by HaKLMTT** [comment]
我们部署了dev-auto-annotate，但是没有发现上一帧，下一帧 以及播放  的 功能按钮。 这三个功能按钮在之前是有的。

**Comment by naurril** [comment]
在右键菜单里面
