### ISSUE TITLE
您好，将来是否会支持在2D图片上使用2D矩形框标注，这样可以方便2D&3D融合标注？

### ISSUE THREAD

**Issue by HaKLMTT** [naurril/SUSTechPOINTS#52]
主要目的是在2D图片上标注2D矩形框，同时可以方便的设置和投影过来的3D框相同的ID，这样可以记录2D框和3D框之间的对应关系

**Comment by yyqgood** [comment]
@naurril 我也有同样的问题；比如：在构建Kitti格式数据集时；在一张图片中，多类多对象的问题时；我们使用你的工具获取3D bbox信息；使用labelimg/labelme获得图像的2D bbox信息；通过这种方式，Kitti格式的标注信息很难对齐，除非使用很多ID

**Comment by naurril** [comment]
有计划，还没有开始动手，大家有想法的可以一起写啊

**Comment by yyqgood** [comment]
@naurril 此外再加上 遮挡和截断 标注信息，那我们的标注工具将十分适配Kitti数据集了；

**Comment by yyqgood** [comment]
> 有计划，还没有开始动手，大家有想法的可以一起写啊

如果时间允许的话，很荣幸和你一起开发

**Comment by naurril** [comment]
> @naurril 此外再加上 遮挡和截断 标注信息，那我们的标注工具将十分适配Kitti数据集了；

遮挡和截断这些，只需要加个属性，标的时候点一下就可以了
