### ISSUE TITLE
how to display the value of length, width and height of the box?

### ISSUE THREAD

**Issue by JuniorZL** [naurril/SUSTechPOINTS#54]

**Comment by naurril** [comment]
It's displaced in the header area, after one box is selected, as shown in this [picture](https://github.com/naurril/SUSTechPOINTS/blob/dev-auto-annotate/doc/main-ui.png), a tip will show up if you stop the cursor over the numbers.

**Comment by JuniorZL** [comment]
I want to display it above the border of the boxes.
