### ISSUE TITLE
关于10hz和2hz功能

### ISSUE THREAD

**Issue by chasingw** [naurril/SUSTechPOINTS#58]
根据README，

> 打开一个场景后，可以先浏览一下，然后开始选定目标物体进行标注．一个场景长20s, 包含40帧原始数据，每秒选取了2帧进行标注．(我们采集的数据是每秒10帧，每帧间隔100ms. 由于间隔时间短，场景变化太小，所以不需要每帧都标注，我们可以根据每秒2帧的标注结果进行线性插值完成对剩余８帧的标注．)

> 对于小目标的物体，如人，在标注的过程中可能不太容易分辩方向，可以根据其前进的方向，相对与建筑／路面的方向等进行辅助判断．　在拥挤场景如果不容易进行追踪，可以切换到10hz的数据(goto/10Hz)进行识别和标注．　10hz的数据和２Hz的数据是共享标注结果的．识别完成后建议切换回2hz,因为10HZ下帧间差距太小，标起来比较浪费时间．

尝试了下 (goto/10Hz) 和 (goto/2Hz) 发现程序从新的路径下去找数据 `原路径_10hz/ 原路径_2hz`，请问这个功能是可用的吗?数据应该怎么给 ?一般标注只标关键帧，还是从关键帧再插值得到所有帧。

**Comment by naurril** [comment]
这是辅助标注用的，数据按照 data/scene_xxx, data/scene_xxx_full_2hz, data/scene_xxx_10hz放，后面两个目录是辅助用的。不过这是我们自己这么用的，根据具体的需求可以用或者不用

**Comment by chasingw** [comment]
> 这是辅助标注用的，数据按照 data/scene_xxx, data/scene_xxx_full_2hz, data/scene_xxx_10hz放，后面两个目录是辅助用的。不过这是我们自己这么用的，根据具体的需求可以用或者不用
> 
> 我晚点加个配置，把这个菜单默认隐藏

多谢回复，这种情况 data/scene_xxx 和 data/scene_xxx_10hz 的数据是一致的吧， 有什么区别吗

**Comment by naurril** [comment]
我们自己的情况，scene_xxx用的是2hz

**Comment by chasingw** [comment]
> 我们自己的情况，scene_xxx用的是2hz

ok 多谢
