### ISSUE TITLE
Predict module missing

### ISSUE THREAD

**Issue by anisghaoui** [naurril/SUSTechPOINTS#6]
I am trying to install it with python3 after pip installing all the packages (predict included). It is still unable to find the package.

sidenote : there should have been a requirement.txt package installation.

have a nice day.

**Comment by naurril** [comment]
Sorry for the inconvenience, the predict module is still in developing, the code is [https://github.com/naurril/DeepAnnotate](https://github.com/naurril/DeepAnnotate), I will upload the pre-trained model in a few days.  For now please just comment predict related lines, thank you very much!

**Comment by naurril** [comment]
I have updated the code to include the `predict` module (actually it is not a public pip package). This will need tensorflow2.1 installed and a pre-trained model downloaded. Please find in `readme` the details. Thank you!

**Comment by anisghaoui** [comment]
will give it a test tomorrow and report. Thank you.

**Comment by anisghaoui** [comment]
I confirm to you that the installation using requirement was correct. as a side note, `wget -p` try to place the model in the folder but then you tell the user to do so. you should either delete the `-p` or modify the  `readme.md`

Thank you.
