### ISSUE TITLE
请问deep_annotation_inference用的是什么算法? Which algorithm is used in Deep annotation inference?

### ISSUE THREAD

**Issue by Tony9006** [naurril/SUSTechPOINTS#62]
请问deep_annotation_inference.h5用的是什么算法，可以推荐相关论文吗，如果有训练代码就更好了，感谢。

May I ask Which algorithm is used in deep_annotation_inference.h5? 
Can you recomend some related papers? 
And it will be appreciated if you can provide the model trainning code.

**Comment by naurril** [comment]
代码 https://github.com/naurril/DeepAnnotate
我们没有对这个算法写论文

**Comment by Tony9006** [comment]
> 代码 https://github.com/naurril/DeepAnnotate 我们没有对这个算法写论文
非常感谢。

**Comment by Tony9006** [comment]
> 代码 https://github.com/naurril/DeepAnnotate 我们没有对这个算法写论文

非常感谢！
