### ISSUE TITLE
Hello, can you give a web source code that has not been compiled？

### ISSUE THREAD

**Issue by zhou1591** [naurril/SUSTechPOINTS#64]
Hello, can you give a web source code that has not been compiled？

**Comment by zhou1591** [comment]
你好，你能提供一个未编译的web源代码吗?

**Comment by naurril** [comment]
开源的就是源代码

**Comment by zhou1591** [comment]
> 开源的就是源代码

啊   刚才看了写确实是  我以为你使用的什么框架 然后编译的呢  

大佬这是什么意思 我拉下来之后直接用docker启动的 
![image]()

**Comment by zhou1591** [comment]
缺的这个目录我补上了  然后 第一个是啥意思  之前没有接触过py

**Comment by zhou1591** [comment]
你这个是有nginx 配置嘛 
![image]()
 我在浏览器打开的时候 报错这个  我看你得静态资源是在public 下边的  然后我也看到py 里边 有写 static  指向了 public  但是没有生效 是什么原因呢

**Comment by naurril** [comment]
这个图能全一点吗，左边挡住的是路径？

**Comment by zhou1591** [comment]
左边是我得域名

**Comment by zhou1591** [comment]
我是直接用docker  启动的 然后 是报了上边那个错  我看他拉了乌班图的镜像  然后 git 同步了代码 什么的

**Comment by zhou1591** [comment]
![image]()

我重启后 他的报错信息

**Comment by naurril** [comment]
这个报错没有影响

**Comment by zhou1591** [comment]
但是他配置没有生效啊  大佬  static  没有找到 public 里边的js 和css

**Comment by zhou1591** [comment]
嗷嗷 是我菜了  不好意思大佬  我代理docker 的时候没有把静态资源拿出来
