### ISSUE TITLE
只支持pcd的lidar文件吗？

### ISSUE THREAD

**Issue by Leozyc-waseda** [naurril/SUSTechPOINTS#67]
我打算用pandaset来进行测试，pandaset的格式是.pkl.gz，如果要用您的工具，是不是必须将.pkl.gz转换成pcd格式？

**Comment by naurril** [comment]
是，只支持pcd和kitti的bin格式两种

**Comment by Leozyc-waseda** [comment]
我打算用npy的格式，具体修改哪部分的代码您有什么建议吗？

**Comment by naurril** [comment]
不需要改代码，把数据转换格式就可以，建议用bin格式，xyzi四个字段，f32类型即可

**Comment by Leozyc-waseda** [comment]
我将npy再转成了pcd格式，如下图所示，xyzi的四个字段，f32类型
![無題の画像](https://user-images.githubusercontent.com/52599722/158107553-cd7d39d2-77ab-4999-abbf-db8e3123d092.png)

在浏览器打开查看了却什么也没有
![1](https://user-images.githubusercontent.com/52599722/158107718-72034b0b-37d5-4874-af23-fa8ac7bb115e.png)

用pcd viewer查看了我的pcd文件，正常显示着点云，请问这是需要修改什么地方吗？
![2](https://user-images.githubusercontent.com/52599722/158107953-551f5a1c-12f0-4f94-8827-2c9388a76280.png)

**Comment by naurril** [comment]
用pcd格式的话，你试试用binary不要compressed

**Comment by naurril** [comment]
增加了对binary_compressed格式的支持，你用最新的版本试试。

**Comment by Leozyc-waseda** [comment]
谢谢你的回复~
我用binary测试成功了，刚刚git pull一下，binary_compressed的文件还是不能显示。。

有3个问题还想要再询问一下，
1.你具体使用什么GPU在运行这个程序？
我用的是1080Ti，没有RT core感觉浏览器很慢很重

2.我想用Deep 3D Object Detection Network来生成初始标注，这部分代码具体在哪里修改有什么建议吗？

3.在ctrl+鼠标左键标注的时候，想取消的话有办法吗？以及标注后想ctrl+z返回前一个状态有办法吗？

**shortcuts_cn.md中**
  | Delete/Ctrl+d | 删除 
| Ctrl | 按住ctrl，用鼠标拖动box，会自动收缩box 
| Shift | 按住shift，用鼠标拖动box，会移动box但保持box大小不变
  | Ctrl+a| 全选
  | Ctrl+s| 保存

上面的操作ubuntu18.04，远程操作下都不能使用


<html>
<body>

  |+/=| 增加点的大小 
  |=| 减小点的大小

<br class="Apple-interchange-newline">
</body>
</html>
实际测试+是增加，-是减小

**Comment by naurril** [comment]
1. 平时操作时与客户端的gpu有关系，主要是一些渲染的操作，没有特别的要求，很慢的话是否点云文件很大
2.  初始标注我们没有提供相应的代码
3. 不能取消，只能删除。也还没有提供ctrl+z的功能。

远程有些操作不能用，是远程软件把shift/ctrl拦截了么，有browser就能用，不远程可以么

**Comment by Leozyc-waseda** [comment]
> 平时操作时与客户端的gpu有关系，主要是一些渲染的操作，没有特别的要求，很慢的话是否点云文件很大

最大支持多少size的文件呀？我用56Mb的文件的话，能打开但是几乎不能操作，如果我把GPU从1080TI换成更好的GPU会改善吗

> 远程有些操作不能用，是远程软件把shift/ctrl拦截了么，有browser就能用，不远程可以么

远程的时候shift/ctrl都能正常使用，browser下操作就不行，不远程的情况还没试过。。

再请问一下，您是怎么校准摄像头和LiDAR之间的数据？
如果有在使用的校准软件可以告诉我吗？

**Comment by naurril** [comment]
autoware有个标定工具 https://autoware.readthedocs.io/en/feature-documentation_rtd/DevelopersGuide/PackagesAPI/sensing/autoware_camera_lidar_calibrator.html

**Comment by Leozyc-waseda** [comment]
您的front.json, left.json, right.json文件中的内参和外参都是用Autoware Camera-LiDAR Calibration Package来调试的吗？

我看example中的left.json文件有一个value是extrinsic_ok这个是什么意思？

鱼眼摄像头能用吗？我看您是使用普通的摄像头的感觉

**Comment by naurril** [comment]
只需要intrinsic 和extrinsic两个字段，extrinsic是雷达到相机的转换。extrinsic_ok是调试忘记删除了。
example里面不是用autoware标的，是我们用自己的工具标的。
鱼眼我没有试过，需要使用去畸变后的图片。

**Comment by Leozyc-waseda** [comment]
http://www.apsipa.org/proceedings/2020/pdfs/0001666.pdf
Fig.3 3D point cloud Bounding Box maps to 2Dimages
图片和您的软件一模一样，你们是有什么关联吗。。？

**Comment by naurril** [comment]
没有关联 啊，粗看了一下，这是拿我们的项目去发的，图片都没有换

**Comment by Leozyc-waseda** [comment]
啊这样笑。。

pretrained model file [deep_annotation_inference.h5](https://github.com/naurril/SUSTechPOINTS/releases/download/0.1/deep_annotation_inference.h5)
这个模型主要是什么作用啊？

**Comment by DerrickXuNu** [comment]
这种算违反学术原则啊，可以发邮件举报的

**Comment by naurril** [comment]
> 啊这样笑。。
> 
> pretrained model file [deep_annotation_inference.h5](https://github.com/naurril/SUSTechPOINTS/releases/download/0.1/deep_annotation_inference.h5) 这个模型主要是什么作用啊？

自动检测目标物体的旋转角度用的

**Comment by Leozyc-waseda** [comment]
好的谢谢~
我看那篇文章的一作也在深圳，以为有什么关联，结果是直接拿去发的啊 :(

**Comment by Leozyc-waseda** [comment]
请问一下，标注文件中的xyz是怎么计算得到的？
是基于世界坐标吗?
![image](https://user-images.githubusercontent.com/52599722/164360676-c6262365-8aec-48cf-b151-27c86df1fe90.png)

如果我想得到bouding box的8个点的坐标请问有什么方法吗？ ：）
比如图下中的车的bounding box，8个点的坐标。
![image](https://user-images.githubusercontent.com/52599722/164360997-5ddd0087-18ad-43c8-8fe6-3cddd9b2164b.png)

**Comment by naurril** [comment]
标注文件中的xyz 就是点云坐标， 转顶点坐标可以参考这里https://github.com/naurril/SUSTechPOINTS/blob/ff6ef03be74eb5efed35f15a814d05c3015113d9/tools/visualize-camera.py#L148

**Comment by Leozyc-waseda** [comment]
> xyz 就是点云坐标

是Bouding box的中心点坐标吗？

**Comment by naurril** [comment]
是

**Comment by Leozyc-waseda** [comment]
感谢你的回复，
BTW,我发现用稍微比较大的BB标注就会导致一下子标注两个车的问题。
![image](https://user-images.githubusercontent.com/52599722/164446166-8de64313-701c-44d0-a1ab-199d1fb88768.png)
![image](https://user-images.githubusercontent.com/52599722/164446204-a161f66d-0db0-46c9-b50c-018118475a7b.png)

我看了您论文中的fitting algorithm, operation中的s，
scale是由标注的框的大小决定的吧，如果scale太大，range c也会变大，导致x加入R`中的点也会变多，最后计算max-min的时候距离变大，导致一下子标注两个框的情况。

**Comment by naurril** [comment]
是有这杨的问题，不好解决

**Comment by Leozyc-waseda** [comment]
> 标注文件中的xyz 就是点云坐标， 转顶点坐标可以参考这里
> 
> https://github.com/naurril/SUSTechPOINTS/blob/ff6ef03be74eb5efed35f15a814d05c3015113d9/tools/visualize-camera.py#L148

你好，我查看了这个Py文件，这好像是用来可视化图像的。
可以的话，能不能教我一下，如果在有标注文件的前提下，如何直接转换成八个顶点坐标啊...
`psr_to_xyz(p,s,r):`
将p,s,r里面的x,y,z作为输入吗？

```
    x=s[0]/2
    y=s[1]/2
    z=s[2]/2
```
  or直将Scale中的0，1，2作为x,y,z就可以了？

**Comment by naurril** [comment]
三个参数分别是position， scale， rotation， 都是三元组
```
def box_to_nparray(box):
    return np.array([
        [box["position"]["x"], box["position"]["y"], box["position"]["z"]],
        [box["scale"]["x"], box["scale"]["y"], box["scale"]["z"]],
        [box["rotation"]["x"], box["rotation"]["y"], box["rotation"]["z"]],
    ])

b = box_to_nparray(box)
p = psr_to_xzy(b[0], b[1], b[2])

```

https://github.com/naurril/SUSTechPOINTS/blob/ff6ef03be74eb5efed35f15a814d05c3015113d9/tools/visualize-camera.py#L175

**Comment by Leozyc-waseda** [comment]
感谢你的回复，早上我又仔细看了一下大概理清楚了思路
https://github.com/naurril/SUSTechPOINTS/blob/ff6ef03be74eb5efed35f15a814d05c3015113d9/tools/visualize-camera.py#L117
https://github.com/naurril/SUSTechPOINTS/blob/ff6ef03be74eb5efed35f15a814d05c3015113d9/tools/visualize-camera.py#L148
https://github.com/naurril/SUSTechPOINTS/blob/ff6ef03be74eb5efed35f15a814d05c3015113d9/tools/visualize-camera.py#L175


先读取标注json文件中的，p,s,r数据，转成np.arrary的形式，
`    #box_to_nparray({"rotation":{"x":0, "y":np.pi/3, "z":np.pi/2}, "position":{"x":1,"y":2,"z":3}, "scale":{"x":10,"y":2,"z":5}})`
传给`psr_to_xyz`的函数，其中通过`euler_angle_to_rotate_matrix`计算相对于x,y,z的角度，最后得到world_coor，里面就是八个顶点的世界坐标吗？

local坐标系指的是lidar的坐标系，world指的是世界坐标系。
将rotation和postion传入`euler_angle_to_rotate_matrix`得到外部矩阵，再将LiDAR帧中的各点与LiDAR外部矩阵相乘，即可实现世界坐标系转换。
是这个思路吗？

我看您用的计算方式是摄像头计算方式，是世界坐标系到摄像头坐标系的计算方式。
这样的计算得到的外部矩阵就是lidar的外部矩阵吗？（不好意思，我刚学Lidar不久很多基础知识还不是很清楚。。）
x,y,z的
![image](https://user-images.githubusercontent.com/52599722/165220923-c8b729e3-681b-4908-a4cf-b77c794b2100.png)

![image](https://user-images.githubusercontent.com/52599722/165220909-4a819581-e844-4af9-af34-1f3e2c3ecee6.png)

 不过要是能直接在Log 界面输出顶点坐标就好了 ：）

**Comment by naurril** [comment]
其实就是box坐标系到点云坐标系的转换，涉及一个旋转加平移。
web代码里面也有一样计算，[这里](https://github.com/naurril/SUSTechPOINTS/blob/139f1381d99de1cf192ade2292ed154adbb4c753/public/js/image.js#L1082)

改成 ```console.log(box.obj_track_id, box3d);``` 在box投影到图像上时会打印8个顶点

**Comment by Leozyc-waseda** [comment]
> 其实就是box坐标系到点云坐标系的转换，涉及一个旋转加平移。
我跟GPS比较了一下，是准确的，感谢！

没有校准好的相机数据，只有lidar数据的情况下可以将八个点输出到log吗？
我现在是读取json file中的p,s,r数据，后通过上面的函数再输出local,world的坐标。。感觉有点麻烦
