### ISSUE TITLE
启动main.py出现的问题

### ISSUE THREAD

**Issue by DavidWZX** [naurril/SUSTechPOINTS#68]
您好，感谢您开源的标注工具，我在配置过程中按照Readme的步骤，在最后python main.py 的时候出现了如下Cherry Checker报错，http://127.0.0.1:8081/ 能打开但是没有载入任何东西。
![2022-03-01 11-26-45 的屏幕截图](https://user-images.githubusercontent.com/65859166/156099683-5bd97d3b-9042-4fab-9913-853ff6271033.png)

**Comment by naurril** [comment]
这个报错没有影响，需要看看前端的错误信息

**Comment by DavidWZX** [comment]
> 这个报错没有影响，需要看看前端的错误信息

感谢您的回复，现在已经可以使用了，是我没注意到要选择页面左上角的data
