### ISSUE TITLE
点云数量过大时，会崩溃和卡顿明显

### ISSUE THREAD

**Issue by hai715** [naurril/SUSTechPOINTS#69]
您好，想请问，我加载有8000000点云点的pcd文件，加载一个文件的时候会有卡顿，但相对还可以正常使用，但是data的lidar文件夹下放入多个文件后，加载过程中网页就会崩溃，请问是什么原因？谢谢

**Comment by hai715** [comment]
还有如果z值太大，以千为单位，网页会直接不显示

**Comment by naurril** [comment]
崩溃可能是内存不足了，你看自动预加载是不是开启了，如果开了默认会把文件夹里面的点云加载几十个

> 您好，想请问，我加载有8000000点云点的pcd文件，加载一个文件的时候会有卡顿，但相对还可以正常使用，但是data的lidar文件夹下放入多个文件后，加载过程中网页就会崩溃，请问是什么原因？谢谢

**Comment by naurril** [comment]
> 还有如果z值太大，以千为单位，网页会直接不显示

这个工具是为交通场景定制的，如果z值过大估计需要调整一些配置（比如camera的设置）可能才能用，鼠标滚轮缩放后能看到吗

**Comment by hai715** [comment]
> > 还有如果z值太大，以千为单位，网页会直接不显示
> 
> 这个工具是为交通场景定制的，如果z值过大估计需要调整一些配置（比如camera的设置）可能才能用，鼠标滚轮缩放后能看到吗

缩放也是看不到的，网页上面没有点云

**Comment by hai715** [comment]
> 崩溃可能是内存不足了，你看自动预加载是不是开启了，如果开了默认会把文件夹里面的点云加载几十个
> 
> > 您好，想请问，我加载有8000000点云点的pcd文件，加载一个文件的时候会有卡顿，但相对还可以正常使用，但是data的lidar文件夹下放入多个文件后，加载过程中网页就会崩溃，请问是什么原因？谢谢

卡的话也跟内存不足有关系么？标注框的时候需要等一会才能显示出框。请问在哪里关闭自动预加载啊，不好意思，我刚学，还不是很理解，多谢。

**Comment by hai715** [comment]
> > 崩溃可能是内存不足了，你看自动预加载是不是开启了，如果开了默认会把文件夹里面的点云加载几十个
> > > 您好，想请问，我加载有8000000点云点的pcd文件，加载一个文件的时候会有卡顿，但相对还可以正常使用，但是data的lidar文件夹下放入多个文件后，加载过程中网页就会崩溃，请问是什么原因？谢谢
> 
> 卡的话也跟内存不足有关系么？标注框的时候需要等一会才能显示出框。请问在哪里关闭自动预加载啊，不好意思，我刚学，还不是很理解，多谢。

我找到那里关预加载了

**Comment by ZhangYida96** [comment]
> > > 崩溃可能是内存不足了，你看自动预加载是不是开启了，如果开了默认会把文件夹里面的点云加载几十个
> > > > 您好，想请问，我加载有8000000点云点的pcd文件，加载一个文件的时候会有卡顿，但相对还可以正常使用，但是data的lidar文件夹下放入多个文件后，加载过程中网页就会崩溃，请问是什么原因？谢谢
> > 
> > 
> > 卡的话也跟内存不足有关系么？标注框的时候需要等一会才能显示出框。请问在哪里关闭自动预加载啊，不好意思，我刚学，还不是很理解，多谢。
> 
> 我找到那里关预加载了

你好，请问那个预加载的设置具体在哪里呢？

**Comment by zheyuanWang** [comment]
> > > 崩溃可能是内存不足了，你看自动预加载是不是开启了，如果开了默认会把文件夹里面的点云加载几十个
> > > > 您好，想请问，我加载有8000000点云点的pcd文件，加载一个文件的时候会有卡顿，但相对还可以正常使用，但是data的lidar文件夹下放入多个文件后，加载过程中网页就会崩溃，请问是什么原因？谢谢
> > 
> > 
> > 卡的话也跟内存不足有关系么？标注框的时候需要等一会才能显示出框。请问在哪里关闭自动预加载啊，不好意思，我刚学，还不是很理解，多谢。
> 
> 我找到那里关预加载了

可以分享一下哪里关预加载/设置预加载上限么

**Comment by heyu3913** [comment]
> > > 崩溃可能是内存不足了，你看自动预加载是不是开启了，如果开了默认会把文件夹里面的点云加载几十个
> > > > 您好，想请问，我加载有8000000点云点的pcd文件，加载一个文件的时候会有卡顿，但相对还可以正常使用，但是data的lidar文件夹下放入多个文件后，加载过程中网页就会崩溃，请问是什么原因？谢谢
> > 
> > 
> > 卡的话也跟内存不足有关系么？标注框的时候需要等一会才能显示出框。请问在哪里关闭自动预加载啊，不好意思，我刚学，还不是很理解，多谢。
> 
> 我找到那里关预加载了

可以分享下在哪个文件修改关闭预加载吗？
