### ISSUE TITLE
Add the land grid and some new pcl data.

### ISSUE THREAD

**Issue by HaomingJu** [naurril/SUSTechPOINTS#7]
Hi I add the Grid on the scene, and add the control switch of the grid.
And add some pcd data without the calib param. 

I will send a merge request if you think that's needed.

**Comment by HaomingJu** [comment]
![image](https://user-images.githubusercontent.com/24786568/78204260-bad62180-74cb-11ea-9510-140852029068.png)

**Comment by naurril** [comment]
That looks awesome, I'd like to merge it, but please disable it by default because I am not sure if the grid is needed for everyone.
For the pcd data, since they are just examples, please keep it small. 
Thank you!

**Comment by HaomingJu** [comment]
Hi, 针对大模型, 推荐使用 git lfs (large file storage)进行管理.
参考: https://git-lfs.github.com/

**Comment by naurril** [comment]
好的，我看一下。你是说把什么文件放到lfs里面？

**Comment by HaomingJu** [comment]
诸如, 前面wget的h5 文件; data/example中的数据, 都可以通过lfs来存储, github默认支持lfs插件.

**Comment by HaomingJu** [comment]
我这里担心贸然用lfs, 这个代码库相关的forker会不习惯.
