### ISSUE TITLE
能否增加视角高亮功能

### ISSUE THREAD

**Issue by DusuWen** [naurril/SUSTechPOINTS#72]
你好，
能否增加在点云图中高亮显示2D图像视角的功能，或者有什么实现思路
谢谢

**Comment by naurril** [comment]
需要计算点云投影到图片之后落在图片内的那些点，修改颜色

**Comment by DusuWen** [comment]
> 

使用相机的内外参吗

**Comment by naurril** [comment]
是的，可以参考这里

https://github.com/naurril/SUSTechPOINTS/blob/e4d34e074348f054f8dfaa912ebc4a0b5f2b09d7/public/js/image.js#L646

**Comment by DusuWen** [comment]
> 是的，可以参考这里
> 
> https://github.com/naurril/SUSTechPOINTS/blob/e4d34e074348f054f8dfaa912ebc4a0b5f2b09d7/public/js/image.js#L646

谢谢

**Comment by DusuWen** [comment]
> 

有两个问题，get_all_points方法在lidar.js里定义的方法名错了；第二个是计算点云中点在Image2D的方法points3d_to_image2d运行缓慢并且也没有得到数据，所以关键的方法就在points3d_to_image2d里了是吧？

**Comment by naurril** [comment]
抱歉这个功能没怎么用，是可能代码有一些问题了。不过点到图像的映射的步骤应该是没有问题的，你也可以去找找其他的参考资料。
我不清楚你的具体需求，是否不需要在标注工具里做，可以先把点云切好，只留你要高亮的部分是不是就可以了。
