### ISSUE TITLE
Cannot render this pcd file

### ISSUE THREAD

**Issue by zoonware** [naurril/SUSTechPOINTS#74]
It seems that this PCD file is no different. Nothing error occurred 
[velodyne64.zip](https://github.com/naurril/SUSTechPOINTS/files/8348971/velodyne64.zip)

**Comment by naurril** [comment]
this is binary_compressed pcd which is not supported in earlier version, please try latest version

**Comment by naurril** [comment]
The points in the file are around (3000,1700,20), but the tool renders points around (0,0,0) by default.

# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z intensity
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 499651
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 499651
DATA ascii
3181.641 1698.578 20.693 1
3180.049 1697.928 20.716 2
3180.137 1697.965 20.74575 2.5
3182.039 1698.78 20.727 0
3205.098 1707.755 20.895 20
3205.085 1707.849 20.897 10
3205.062 1707.967 20.898 9
3188.876 1701.607 20.999 11
3189.934 1701.888 20.999 33
3189.903 1701.946 20.994 19
3189.899 1702.048 20.994 12
3189.892 1702.117 20.994 13
3190.651 1702.154 20.999 40
3190.723 1702.197 20.994 39.5
3189.898 1702.204 20.997 14
3190.675 1702.257 20.9865 15.5
3190.775 1702.27 20.998 23
3190.817 1702.233 20.99734 39.66667
3189.888 1702.365 20.9975 22
3190.648 1702.358 20.9926 18.4
3190.75 1702.324 20.998 19.33333

**Comment by naurril** [comment]
fixed the problem, you can check out the latest code and use 'reset view' (context menu) to move points into view.

**Comment by zoonware** [comment]
Thanks so much  @naurril

**Comment by cll5854** [comment]
这个问题我获取了最新的，还是加载不出来呢
