### ISSUE TITLE
pcd 

### ISSUE THREAD

**Issue by gc625** [naurril/SUSTechPOINTS#77]
Hi, I used open3d to convert some radar data into pcd, and write_point_cloud should write in binary by default, code is as follows:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/29677319/163692924-53c91510-a356-4dcf-9da1-31c704106538.png">

However, when viewed in the GUI, it appears in this lattice shape:
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/29677319/163692973-706fdd27-20b0-4e03-a68a-386c603b0d38.png">

but when viewed with another pcd viewer it shows normally like so, 
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/29677319/163692985-6660f250-939c-48fd-8004-60c436b40717.png">

any suggestions?

**Comment by naurril** [comment]
May I see the PCD file header？

**Comment by gc625** [comment]
For sure, here:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/29677319/163731769-c40702c3-f157-4ce6-941b-394b68c62bed.png">

**Comment by naurril** [comment]
Added a fix to support float64 for PCD file, please check out the newest version and try again.  
Better clean browser cache before reloading (ctrl+reload for Chrome)

Thanks.

**Comment by gc625** [comment]
great, it works now. Thanks a lot!
