### ISSUE TITLE
Cannot add new box by 'Holding Ctrl, draw a rectangle`

### ISSUE THREAD

**Issue by shiqi1994** [naurril/SUSTechPOINTS#78]
Thank you for your great work!

I installed this annotation tool from source. When I tried to add 3D bbox, only right click worked. There was no response when I held Ctrl and left click to draw a rectangle.

Could you please help on this issue? 
Thanks again!

**Comment by naurril** [comment]
Hi, just a reminder that you need to hold and move the left button when drawing the rectangle, or, if the problem persists, please provide the browser type and console log (F12 for chrome)
