### ISSUE TITLE
项目启动后一片空白

### ISSUE THREAD

**Issue by a873054267** [naurril/SUSTechPOINTS#79]
是需要拖入Pcd的点云数据还是怎么操作呢？在界面上未见导入的按钮

**Comment by a873054267** [comment]
> 是需要拖入Pcd的点云数据还是怎么操作呢？在界面上未见导入的按钮

![image](https://user-images.githubusercontent.com/30728610/166136456-9b9b4f8b-1014-43a6-b311-d5323ef26c57.png)

**Comment by naurril** [comment]
选scene和frame

**Comment by a873054267** [comment]
> 选scene和frame
我选过，但是没反应，我看控制台打印的example对象为空

**Comment by a873054267** [comment]
> 选scene和frame
我选过，但是也没反应，我看控制台打印的example对象为空；不知道是不是要在后台预先放置一些数据？

**Comment by naurril** [comment]
example里面的数据没有了吗

**Comment by a873054267** [comment]
> example里面的数据没有了吗

我看文件夹中是有的，但返回的没有
![image](https://user-images.githubusercontent.com/30728610/166907576-6f20ef24-d423-4912-9bbb-e65598f63008.png)

**Comment by naurril** [comment]
请看一下服务端的log里面有报错没有，发来看看

**Comment by a873054267** [comment]
> 请看一下服务端的log里面有报错没有，发来看看
这个是启动的时候报错，我前台访问网页的时候没报错
![image](https://user-images.githubusercontent.com/30728610/167051270-3f0395d1-de5c-4fb6-bd44-829ddbc9e663.png)

**Comment by naurril** [comment]
先选scene，再选frame，是这么操作的吗

**Comment by a873054267** [comment]
> 先选scene，再选frame，是这么操作的吗

是的，方便的话留一下微信/QQ请教一下您吧；
我QQ/微信：873054267

**Comment by Beforcer** [comment]
我也是这种情况，怎么解决的啊
