### ISSUE TITLE
[Request] Enforce label 

### ISSUE THREAD

**Issue by anisghaoui** [naurril/SUSTechPOINTS#8]
When drawing a cuboid on a region, is there any possibility to select the desired Label and override the automatic labelling without having to modify the JSON.

Thank you.

**Comment by naurril** [comment]
When a cuboid is selected,  a floating toolbox will appear, you can change label by selecting one in the drop-down list, is this what you want?

**Comment by naurril** [comment]
When a cuboid is selected,  a floating toolbox will appear, you can change label by selecting one in the drop-down list, is this what you want?
![Screenshot_2020-04-03-09-50-01-376_TeamViewer](https://user-images.githubusercontent.com/7512334/78315875-d2c3a900-7590-11ea-8b1b-f4a9f7f50231.png)

**Comment by naurril** [comment]
When a cuboid is selected,  a floating toolbox will appear, you can change label by selecting one in the drop-down list, is this what you want?

**Comment by anisghaoui** [comment]
Exactly, 

in my case, nothing drops down (firefox Ubuntu 18.04). I does work in Chromium however. 

![image](https://user-images.githubusercontent.com/37940201/78338228-aa3cae80-7592-11ea-95c0-4732cc8f86b5.png)


Your tool is amazing, thank you.
