### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.check_labels'

### ISSUE THREAD

**Issue by cwlroda** [naurril/SUSTechPOINTS#80]
Hi, I've got this error when installing the project from source and then running `main.py`:

![image](https://user-images.githubusercontent.com/47574881/168256216-36f3bfb4-d4bd-44de-886e-98def129fa60.png)

It can be fixed by adding an empty `__init__.py` file in the `tools` folder so that the module is visible.
Was wondering if this could be fixed directly, or I can open a PR for this too.

**Comment by naurril** [comment]
Hi, I changed the import statements ([commit](https://github.com/naurril/SUSTechPOINTS/commit/43f5e6cb6331653f32c501c08044598849e1450a)) to ```from tools import ... ``` and tested in my ubuntu, please help test it in your system at your convenience, thanks.

**Comment by cwlroda** [comment]
Yes, this works, thanks!
