### ISSUE TITLE
请问一下保存标注的.json逻辑代码在哪个部分呀？

### ISSUE THREAD

**Issue by Leozyc-waseda** [naurril/SUSTechPOINTS#81]
你好~

目前步骤是画好2D bbox后，用Fitting algorithm来生成3D bbox，然后自动保存在label文件夹中。
这个逻辑的代码具体在哪里啊？

我搜了关键词.json, ./label
https://github.com/naurril/SUSTechPOINTS/blob/c1feb267014d137d4d4accc9bcea9a5c188378e8/scene_reader.py#L241
好像都不对...  :(

**Comment by naurril** [comment]
前端文件是save.js

**Comment by Leozyc-waseda** [comment]
https://github.com/naurril/SUSTechPOINTS/blob/139f1381d99de1cf192ade2292ed154adbb4c753/main.py#L81-L82

找到了！这个是吧

Fitting algorithm在哪里可以告诉我吗 :)

**Comment by Leozyc-waseda** [comment]
我将数据打印出来看了一下，很好奇为什么 Data里面会有两个一模一样的scene保存在一个 json file里面？
![image](https://user-images.githubusercontent.com/52599722/168937842-5cf04fd8-59e8-4edb-8efc-15d93a767080.png)

**Comment by naurril** [comment]
> https://github.com/naurril/SUSTechPOINTS/blob/139f1381d99de1cf192ade2292ed154adbb4c753/main.py#L81-L82
> 
> 找到了！这个是吧
> 
> Fitting algorithm在哪里可以告诉我吗 :)

box_op.js, 函数 auto_rotate_xyz

**Comment by naurril** [comment]
> 我将数据打印出来看了一下，很好奇为什么 Data里面会有两个一模一样的scene保存在一个 json file里面？ ![image](https://user-images.githubusercontent.com/52599722/168937842-5cf04fd8-59e8-4edb-8efc-15d93a767080.png)

看起来是重复保存了，之前有这样的问题，你换最新的版本试试

**Comment by Leozyc-waseda** [comment]
我想改变一下键盘的rotation的强度，现在的旋转有点太敏感了，代码应该在这里吧，
` this.editorCfg.rotateStep/4`没有效果，`this.selected_box.rotation.z += 0.0025`,也没有效果。。具体在哪里可以调节呢？

https://github.com/naurril/SUSTechPOINTS/blob/a0f9aedce6229abb8858e41535b22db517a86d30/public/js/editor.js#L1972-L1977
https://github.com/naurril/SUSTechPOINTS/blob/a0f9aedce6229abb8858e41535b22db517a86d30/public/js/editor.js#L2138-L2149

然后我觉得鸟瞰图，侧视图，前视图的windows尺寸有点太小了，调节视图尺寸这个的代码在哪里可以告诉我吗？
![image](https://user-images.githubusercontent.com/52599722/169187022-03289eab-42c6-40e8-8e83-60e2d6c66522.png)

十分感谢！

**Comment by naurril** [comment]
```this.editorCfg.rotateStep``` 这是个参数，调旋转灵敏度改这个值就行了。
几个视图的大小要调节的话，可以鼠标拖动最下面的照片视图的右下脚，也可以直接改css修改元素的大小```#main-box-editor-wrapper #sub-views```

**Comment by Leozyc-waseda** [comment]
如果只是一个参数的话，*100就增加了100倍吧，我测试了一下，没有任何效果，即使我将`this.editorCfg.rotateStep`设置为0，也会继续转动，而且我还加了个logger.log语句，并没有看见任何输出，数据没有经过这个地方。。。
![image](https://user-images.githubusercontent.com/52599722/169215442-4507e34c-8a2b-4813-8f0a-9240a09e11d8.png)
注释了代码也正常可以转动。。
![image](https://user-images.githubusercontent.com/52599722/169219492-fa517378-9a0d-4b1a-8780-48438dbc61ac.png)

这里的我也改了试了试，没反应...
https://github.com/naurril/SUSTechPOINTS/blob/139f1381d99de1cf192ade2292ed154adbb4c753/public/js/config.js#L41-L42

**Comment by naurril** [comment]
应该是代码没有刷新，清空一下缓存

**Comment by Leozyc-waseda** [comment]
我重启了电脑还是这样。。注释了代码也正常可以转动。。

**Comment by naurril** [comment]
> 我重启了电脑还是这样。。注释了代码也正常可以转动。。

要清浏览器缓存，chrome的话用ctrl+reload

**Comment by Leozyc-waseda** [comment]
Yes, you are right.
非常Thanks♪ﾉ，学习了！

**Comment by naurril** [comment]
可以换react-app分支调试，不会有这个刷新的问题，需要npm [使用说明](https://github.com/naurril/SUSTechPOINTS/blob/react-app/doc/install_from_source.md#test-frontend)

**Comment by Leozyc-waseda** [comment]
十分感谢，我试试  ：）

**Comment by Leozyc-waseda** [comment]
请问您是怎么解决当前frame中的物体，与之前frame的物体是否属于同一个物体，的id生成的问题呢？

**Comment by naurril** [comment]
> 请问您是怎么解决当前frame中的物体，与之前frame的物体是否属于同一个物体，的id生成的问题呢？

不是按这个逻辑设计的，是先标好某帧一个obj，然后用算法或者手工在其他帧把这个obj全标上，id就是跟着copy过去的。

**Comment by Leozyc-waseda** [comment]
原来如此，感谢解答！
BTW，如果我想自定义一个Button在main UI上面，我应该在哪里更改呢？

**Comment by naurril** [comment]
可以参考 `save-button`

**Comment by Leozyc-waseda** [comment]
你好，我在`index.html`中增加了
```
<div class="menu-item" id="cfg-new-button">
 <span>new button</span>
</div>
```
在`config_ui.js`中增加了

```
        "#cfg-new-button": (event)=>{
            logger.log("new button ");
            return true;
        },
```
我想点击这个newbutton后，可以打开新的terminal然后执行sh文件，或者直接执行sh文件，这是可能的吗？

**Comment by naurril** [comment]
不能

**Comment by Leozyc-waseda** [comment]
![image](https://user-images.githubusercontent.com/52599722/172273067-b4c291bf-253b-4928-bdb4-a342e93296bd.png)
这个黄色的圆圈的半径代表着多少m啊？

**Comment by naurril** [comment]
30,50,100m

**Comment by Leozyc-waseda** [comment]
Thanks!
