### ISSUE TITLE
运行main.py之后127.0.0.1:8081页面空白

### ISSUE THREAD

**Issue by Qiu-Jialuo** [naurril/SUSTechPOINTS#86]
您好，我在运行main.py之后显示ENGINE Bus STARTED，打开浏览器进入127.0.0.1:8081页面空白，请问您知道怎么解决这个问题吗？

**Comment by Qiu-Jialuo** [comment]
![1](https://user-images.githubusercontent.com/96973016/175859007-a9a0f372-6446-4373-9985-164d73a0c9fd.png)

**Comment by Qiu-Jialuo** [comment]
![2](https://user-images.githubusercontent.com/96973016/175859328-3e023779-ae79-43eb-b67e-12d77a0fb6a3.png)

**Comment by Beforcer** [comment]
我也是这样，你是怎么解决的啊

**Comment by echo-machile** [comment]
怎么解决呀

**Comment by Beforcer** [comment]
我一开始在win10下运行的，后来用Ubuntu就没问题了



***@***.***
 
发件人： 刘广全
发送时间： 2022-10-10 09:23
收件人： naurril/SUSTechPOINTS
抄送： Beforcer; Comment
主题： Re: [naurril/SUSTechPOINTS] 运行main.py之后127.0.0.1:8081页面空白 (Issue #86)
怎么解决呀
