### ISSUE TITLE
摄像头校准问题

### ISSUE THREAD

**Issue by Leozyc-waseda** [naurril/SUSTechPOINTS#89]
```
back_camera:
  extrinsic:
    transform:
      rotation: {w: 0.713789231075861, x: 0.7003585531940812, y: -0.001595758695393934,
        z: -0.0005330311533742299}
      translation: {x: -0.0004217634029916384, y: -0.21683144949675118, z: -1.0553445472201475}
  intrinsic:
    D: [-0.1619, 0.0113, -0.00028815, -7.9827e-05, 0.0067]
    K: [933.4667, 0, 896.4692, 0, 934.6754, 507.3557, 0, 0, 1]
front_camera:
  extrinsic:
    transform:
      rotation: {w: 0.016213200031258722, x: 0.0030578899383849464, y: 0.7114721800418571,
        z: -0.7025205466606356}
      translation: {x: 0.0002585796504896516, y: -0.03907777167811011, z: -0.0440125762408362}
  intrinsic:
    D: [-0.5894, 0.66, 0.0011, -0.001, -1.0088]
    K: [1970.0131, 0, 970.0002, 0, 1970.0091, 483.2988, 0, 0, 1]
front_gt:
  extrinsic:
    transform:
      rotation: {w: 0.021475754959146356, x: -0.002060907279494794, y: 0.01134678181520767,
        z: 0.9997028534282365}
      translation: {x: -0.000451117754, y: -0.605646431446, z: -0.301525235176}
front_left_camera:
  extrinsic:
    transform:
      rotation: {w: 0.33540022607039827, x: 0.3277491469609924, y: -0.6283486651480494,
        z: 0.6206973014480826}
      translation: {x: -0.25842240863267835, y: -0.3070654284505582, z: -0.9244245686318884}
  intrinsic:
    D: [-0.165, 0.0099, -0.00075376, 5.3699e-05, 0.01]
    K: [929.8429, 0, 972.1794, 0, 930.0592, 508.0057, 0, 0, 1]
front_right_camera:
  extrinsic:
    transform:
      rotation: {w: 0.3537633879725252, x: 0.34931795852655334, y: 0.6120314641083645,
        z: -0.6150170047424814}
      translation: {x: 0.2546935700219631, y: -0.24929449717803095, z: -0.8686597280810242}
  intrinsic:
    D: [-0.1614, -0.0027, -0.00029662, -0.00028927, 0.0181]
    K: [930.0407, 0, 965.0525, 0, 930.0324, 463.4161, 0, 0, 1]
left_camera:
  extrinsic:
    transform:
      rotation: {w: 0.5050391917998245, x: 0.49253073152800625, y: -0.4989265501075421,
        z: 0.503409565706149}
      translation: {x: 0.23864835336611942, y: -0.2801448284013492, z: -0.5376795959387791}
  intrinsic:
    D: [-0.1582, -0.0266, -0.00015221, 0.00059011, 0.0449]
    K: [930.4514, 0, 991.6883, 0, 930.0891, 541.6057, 0, 0, 1]
main_pandar64:
  extrinsic:
    transform:
      rotation: {w: 1.0, x: 0.0, y: 0.0, z: 0.0}
      translation: {x: 0.0, y: 0.0, z: 0.0}
right_camera:
  extrinsic:
    transform:
      rotation: {w: 0.5087448402081216, x: 0.4947520981649951, y: 0.4977829953071897,
        z: -0.49860920419297333}
      translation: {x: -0.23097163411257893, y: -0.30843497058841024, z: -0.6850441215571058}
  intrinsic:
    D: [-0.1648, 0.0191, 0.0027, -8.5282e-07, -9.6983e-05]
    K: [922.5465, 0, 945.057, 0, 922.4229, 517.575, 0, 0, 1]
```

这是Pandaset的校准文件，我看您之前说的，
https://github.com/naurril/SUSTechPOINTS/issues/84#issuecomment-1161386981
可以转换成，

```
{
"extrinsic": [ -0.9994556,  0.0271314,  0.0187740, 0.0002585796504896516,
  -0.0184290,  0.0129111, -0.9997468, -0.03907777167811011,
  -0.0273669, -0.9995485, -0.0124040, -0.0440125762408362,
0,0,0,1],
"intrinsic":[1970.0131, 0, 970.0002, 0, 1970.0091, 483.2988, 0, 0, 1]
}
```

我实际转换之后并没有在图像上显示任何Box，跟坐标系有关系吗？
![image](https://user-images.githubusercontent.com/52599722/177279241-2dafd125-e6e7-405b-a27a-3a759c259ee5.png)

**Comment by naurril** [comment]
你发一帧数据给我试试

**Comment by Leozyc-waseda** [comment]
[pandaset.zip](https://github.com/naurril/SUSTechPOINTS/files/9045642/pandaset.zip)

上传啦

**Comment by naurril** [comment]
看了一下pandaset的文档，应该是点云都转成world坐标系了，相机每帧有world坐标系下的pose，也就是说每帧都用相机pose当外参就行，和内参乘。这个工具最新的版本也支持每帧有单独的外参
需要下面的pose.json和intrinsics.json
├── camera
│   ├── back_camera
│   │   ├── 00.jpg
│   │   .
│   │   .
│   │   .
│   │   ├── 79.jpg
│   │   ├── intrinsics.json
│   │   ├── poses.json
│   │   └── timestamps.json

这是我自己大致调了一下的图
![image](https://user-images.githubusercontent.com/7512334/177585409-63554f5a-6876-4f6c-84d9-18589a3a41fb.png)

**Comment by Leozyc-waseda** [comment]
[pandaset_calib_camera.zip](https://github.com/naurril/SUSTechPOINTS/files/9059289/pandaset_calib_camera.zip)

pose.json和intrinsics.json我上传到pandaset_calib_camera.zip文件中了。

> pose当外参就行，和内参乘

这句话是什么意思啊？ pose文件中只有position, heading的数据用他们当外参吗？

pose.json
>[{"position": {"x": 0.4089946812412687, "y": 0.2613134190711932, "z": 1.8091555545899585}, "heading": {"w": 0.6578225673496162, "x": -0.6474123760158749, "y": 0.28335991415664824, "z": -0.2604493123741657}}, {"position": {"x": 0.949616007909577, "y": 0.8101681919803494, "z": 1.8218365767094171}, "heading": {"w": 0.6584078044422097, "x": -0.6473552920891482, "y": 0.28054678334854116, "z": -0.262152229070342}}, {"position": {"x": 1.4953531464634382, "y": 1.3697107693113866, "z": 1.8229269465585776}, "heading": {"w": 0.6596810375563803, "x": -0.6467628049330736, "y": 0.2774530375426066, "z": -0.2637017535057771}}, {"position": {"x": 2.0503024330892305, "y": 1.934630238620651, "z": 1.8202559596936638}, "heading": {"w": 0.6614217710627224, "x": -0.6456387384527035, "y": 0.2753404619708932, "z": -0.2643094591101656}}, {"position": {"x": 2.6255698263744454, "y": 2.5055224151466993, "z": 1.8234828284764029}, "heading": {"w": 0.6625417800471792, "x": -0.6448410236294659, "y": 0.2746458491785849, "z": -0.264174377003886}}, {"position": {"x": 3.2119867161964337, "y": 3.091357720002707, "z": 1.8346171891057477}, "heading": {"w": 0.662214009330857, "x": -0.6450406185564035, "y": 0.275456331918482, "z": -0.26366458894652217}}, {"position": {"x": 3.800267288499205, "y": 3.687367285072036, "z": 1.8527902768531095}, "heading": {"w": 0.6610633941720622, "x": -0.6461748408815036, "y": 0.27483274243957645, "z": -0.2644243324291813}}, {"position": {"x": 4.382135620013343, "y": 4.289991634800165, "z": 1.8749888395096164}, "heading": {"w": 0.6605076162405211, "x": -0.6468444908169068, "y": 0.2721595636791888, "z": -0.26692895213152557}}, {"position": {"x": 4.96918035222952, "y": 4.891241833449694, "z": 1.8852680408055518}, "heading": {"w": 0.6613675022298938, "x": -0.645999801757082, "y": 0.269918927058864, "z": -0.26911160498832587}}, {"position": {"x": 5.568349362066724, "y": 5.496034476199233, "z": 1.8978777669331177}, "heading": {"w": 0.6629367059807107, "x": -0.6445787657977848, "y": 0.26889808188531517, "z": -0.26967936536644155}}, {"position": {"x": 6.17494578770428, "y": 6.1076492919769185, "z": 1.9154826337541917}, "heading": {"w": 0.6633308943609505, "x": -0.6443920240538018, "y": 0.2681226953122211, "z": -0.26992825746974924}}, {"position": {"x": 6.7875939610128615, "y": 6.733830672635018, "z": 1.929247994371358}, "heading": {"w": 0.6615673682657592, "x": -0.6464757561002128, "y": 0.2672926937220553, "z": -0.27009688984396346}}, {"position": {"x": 7.410126206073955, "y": 7.367583261893775, "z": 1.953860976260252}, "heading": {"w": 0.6587497368482188, "x": -0.6498410338151652, "y": 0.2681095041893856, "z": -0.268090859105194}}, {"position": {"x": 8.039355000636283, "y": 8.012100057381339, "z": 1.9612312035368065}, "heading": {"w": 0.6554409768313368, "x": -0.6538654828681806, "y": 0.2682739071140202, "z": -0.266244562321414}}, {"position": {"x": 8.666459213172926, "y": 8.661147160653158, "z": 1.968620289080714}, "heading": {"w": 0.6527777506242044, "x": -0.6570201145696407, "y": 0.2678380663643436, "z": -0.2654591259442957}}, {"position": {"x": 9.29341005098644, "y": 9.307442958338179, "z": 1.9636846351417936}, "heading": {"w": 0.6529699935662099, "x": -0.6571255915434372, "y": 0.26737167133968337, "z": -0.26519527485582256}}, {"position": {"x": 9.92158159325656, "y": 9.95872604573066, "z": 1.963029673368667}, "heading": {"w": 0.6537044827167557, "x": -0.6567987249871998, "y": 0.2660013377489678, "z": -0.26557329016105247}}, {"position": {"x": 10.554455662327149, "y": 10.61737722617267, "z": 1.9522745387808667}, "heading": {"w": 0.6543280999821224, "x": -0.6567668248750929, "y": 0.2640247168272365, "z": -0.2660883767126474}}, {"position": {"x": 11.195724552560321, "y": 11.2914090849383, "z": 1.945412409022557}, "heading": {"w": 0.652344414415141, "x": -0.6592249806282958, "y": 0.2628911436532726, "z": -0.2660027001473176}}, {"position": {"x": 11.84614629239457, "y": 11.979787003222862, "z": 1.9430383073057398}, "heading": {"w": 0.6485940289256598, "x": -0.6634787633189889, "y": 0.2614402298445458, "z": -0.26602767240555264}}, {"position": {"x": 12.496319987547245, "y": 12.665602786962095, "z": 1.9332716801585461}, "heading": {"w": 0.6479593775866913, "x": -0.6644528935748707, "y": 0.26155469007019955, "z": -0.26502856698803273}}, {"position": {"x": 13.149682766887938, "y": 13.356925445024443, "z": 1.9161253491294492}, "heading": {"w": 0.6474782758845586, "x": -0.6654030938413029, "y": 0.2597705556524543, "z": -0.26557459099092295}}, {"position": {"x": 13.80092301518271, "y": 14.054960062791936, "z": 1.8908519612572945}, "heading": {"w": 0.6473762759562358, "x": -0.6655754635368147, "y": 0.25728483892613613, "z": -0.2678017388396519}}, {"position": {"x": 14.460862131506866, "y": 14.76243837812915, "z": 1.8676121332112512}, "heading": {"w": 0.6468282601569241, "x": -0.6661639003803942, "y": 0.25600296903675035, "z": -0.26888908407876033}}, {"position": {"x": 15.137712409872693, "y": 15.468076441544477, "z": 1.855797282468388}, "heading": {"w": 0.6476338987830595, "x": -0.6657929886831977, "y": 0.2563993615853314, "z": -0.2674871898726799}}, {"position": {"x": 15.818930134088877, "y": 16.168984391359015, "z": 1.8305696664997684}, "heading": {"w": 0.6498242330495563, "x": -0.6641423939507313, "y": 0.25704840353659425, "z": -0.26564913878692525}}, {"position": {"x": 16.50298091562338, "y": 16.885019665167484, "z": 1.8206833089503756}, "heading": {"w": 0.6513436012874926, "x": -0.6627420481349006, "y": 0.2577953279746641, "z": -0.2646999425202647}}, {"position": {"x": 17.197609032282095, "y": 17.60097623322851, "z": 1.8022947996069694}, "heading": {"w": 0.6522498904941563, "x": -0.6620159773311868, "y": 0.25967554937451315, "z": -0.26243767863178247}}, {"position": {"x": 17.894241224973104, "y": 18.334025215594277, "z": 1.7985750075826032}, "heading": {"w": 0.6516920313274344, "x": -0.663092955919585, "y": 0.25946267224872227, "z": -0.26131274332435694}}, {"position": {"x": 18.586155409790642, "y": 19.078776531559306, "z": 1.7818249632880403}, "heading": {"w": 0.6513748824460402, "x": -0.6636377130737385, "y": 0.2580941042672349, "z": -0.26207476346866904}}, {"position": {"x": 19.278178862504717, "y": 19.825184558083972, "z": 1.7625380628876026}, "heading": {"w": 0.6510355287499661, "x": -0.6641236799848866, "y": 0.2569264640228166, "z": -0.2628331601478692}}, {"position": {"x": 19.978404406688387, "y": 20.583265299975697, "z": 1.7465665184185957}, "heading": {"w": 0.6499671119101501, "x": -0.6653148737191423, "y": 0.25607517716048245, "z": -0.26329522571722946}}, {"position": {"x": 20.685934248281875, "y": 21.346361674261956, "z": 1.7276495052814955}, "heading": {"w": 0.6480112301418031, "x": -0.6675074091706024, "y": 0.25568617266853244, "z": -0.26294464325894584}}, {"position": {"x": 21.40535827543086, "y": 22.106370542561212, "z": 1.7072083321640132}, "heading": {"w": 0.6470759499309847, "x": -0.6685197393572031, "y": 0.25756702429057704, "z": -0.26083194035391444}}, {"position": {"x": 22.12841991683987, "y": 22.861913423883777, "z": 1.6862246981331348}, "heading": {"w": 0.6490835261619523, "x": -0.6665828478017285, "y": 0.2597520960393956, "z": -0.2586246927206367}}, {"position": {"x": 22.852660033240202, "y": 23.61420038772623, "z": 1.661818684951937}, "heading": {"w": 0.6526438479477591, "x": -0.6632376637268474, "y": 0.2608651938036998, "z": -0.25714035041559036}}, {"position": {"x": 23.590493050448245, "y": 24.36225192427284, "z": 1.6333380303632081}, "heading": {"w": 0.6571688157306819, "x": -0.658767483887828, "y": 0.2647955923448982, "z": -0.2530569976861878}}, {"position": {"x": 24.343366239084325, "y": 25.12721039267269, "z": 1.6210095270660636}, "heading": {"w": 0.6588475243904979, "x": -0.6570389249269498, "y": 0.26903714913005033, "z": -0.2486740901729099}}, {"position": {"x": 25.09458911852788, "y": 25.908254256077242, "z": 1.610013522106775}, "heading": {"w": 0.6580971215064245, "x": -0.6576663041951527, "y": 0.27186613846674007, "z": -0.24591058079397346}}, {"position": {"x": 25.843959783212863, "y": 26.69880071291611, "z": 1.595655420497914}, "heading": {"w": 0.65701771107198, "x": -0.6586562340188727, "y": 0.27358491833547455, "z": -0.24423551172010785}}, {"position": {"x": 26.592088538479945, "y": 27.487996313998515, "z": 1.5819463722381921}, "heading": {"w": 0.6578893511324725, "x": -0.6577179859440684, "y": 0.2745153662569563, "z": -0.2433720738313686}}, {"position": {"x": 27.338114238068364, "y": 28.27221566571427, "z": 1.563634879239698}, "heading": {"w": 0.6606624330084659, "x": -0.6548677952348697, "y": 0.2748878638740307, "z": -0.24312544636530078}}, {"position": {"x": 28.086647042092373, "y": 29.062832364956442, "z": 1.5497392614625216}, "heading": {"w": 0.6632454761504981, "x": -0.6522121421335119, "y": 0.27513149209155274, "z": -0.2429555969287181}}, {"position": {"x": 28.845701221181436, "y": 29.86036325074953, "z": 1.5445039775676326}, "heading": {"w": 0.6642526606036616, "x": -0.6512409781261405, "y": 0.27596158346181393, "z": -0.24186524294224554}}, {"position": {"x": 29.60929288649685, "y": 30.667735085531838, "z": 1.5425188403307561}, "heading": {"w": 0.6644110521826557, "x": -0.6512419146247017, "y": 0.27661512330828275, "z": -0.24067819994887577}}, {"position": {"x": 30.372265555012397, "y": 31.481449082566076, "z": 1.5461174951768348}, "heading": {"w": 0.6641789540310717, "x": -0.651798172673901, "y": 0.27639809412971833, "z": -0.24006156019365776}}, {"position": {"x": 31.13172081965443, "y": 32.29963232516163, "z": 1.5489193987898353}, "heading": {"w": 0.6647989559880124, "x": -0.6515747420211294, "y": 0.2750993161107006, "z": -0.24044348598531712}}, {"position": {"x": 31.889367683852775, "y": 33.125738911389334, "z": 1.5485190782915732}, "heading": {"w": 0.6655638809862809, "x": -0.6514227923694775, "y": 0.2730271464120797, "z": -0.2411000689135271}}, {"position": {"x": 32.64779461172116, "y": 33.96112153542479, "z": 1.5466162300677289}, "heading": {"w": 0.6653460378256817, "x": -0.6524063965218356, "y": 0.270636335877154, "z": -0.24173646276481994}}, {"position": {"x": 33.41353591986847, "y": 34.80492277127658, "z": 1.5472717379335512}, "heading": {"w": 0.6644029247775785, "x": -0.6540388788750878, "y": 0.26910456082213274, "z": -0.2416291245101543}}, {"position": {"x": 34.18107369177592, "y": 35.65778446259352, "z": 1.5506440621606083}, "heading": {"w": 0.6633190718603188, "x": -0.6558241393568793, "y": 0.2674103897031669, "z": -0.24164889948429946}}, {"position": {"x": 34.944486006499005, "y": 36.51186613653294, "z": 1.5490381397152027}, "heading": {"w": 0.6629246792346888, "x": -0.6569327189487014, "y": 0.2648780119043397, "z": -0.2425075488430301}}, {"position": {"x": 35.70762039452919, "y": 37.36870417579726, "z": 1.5488443196150943}, "heading": {"w": 0.663632379883605, "x": -0.6569444220178122, "y": 0.2624026935201721, "z": -0.2432301732578894}}, {"position": {"x": 36.468681475433876, "y": 38.23061058763356, "z": 1.544772594001207}, "heading": {"w": 0.6648083332020333, "x": -0.6565741739560657, "y": 0.2591891151047546, "z": -0.2444611151292934}}, {"position": {"x": 37.22968095867572, "y": 39.10237099041249, "z": 1.5442069455030816}, "heading": {"w": 0.6651145467082149, "x": -0.6570765493007195, "y": 0.2558221295605215, "z": -0.245821248356002}}, {"position": {"x": 37.99753569499132, "y": 39.98577040184703, "z": 1.5532178423847078}, "heading": {"w": 0.6645182787249355, "x": -0.6584628420712968, "y": 0.2533572807233463, "z": -0.2462767369369456}}, {"position": {"x": 38.767675709670726, "y": 40.874729309822094, "z": 1.5619170444561827}, "heading": {"w": 0.6637339154926608, "x": -0.6601130761695685, "y": 0.2508776073110089, "z": -0.24651256001395266}}, {"position": {"x": 39.53941181728508, "y": 41.7692001988996, "z": 1.56792254756858}, "heading": {"w": 0.6635825633412253, "x": -0.6609975054601005, "y": 0.24891581974879262, "z": -0.24653882875481853}}, {"position": {"x": 40.314103638095176, "y": 42.66608872352158, "z": 1.5706899822298588}, "heading": {"w": 0.6637909219266998, "x": -0.6614066123637474, "y": 0.24729329613540485, "z": -0.24651355089669927}}, {"position": {"x": 41.09090401260821, "y": 43.5682571456981, "z": 1.5729231010030937}, "heading": {"w": 0.6639394091630731, "x": -0.661759105292087, "y": 0.24577996169153324, "z": -0.2466810855215955}}, {"position": {"x": 41.8705178962101, "y": 44.47503772312409, "z": 1.5744250752929878}, "heading": {"w": 0.6637297755276229, "x": -0.66230174705315, "y": 0.24488298511610243, "z": -0.2466809772337989}}, {"position": {"x": 42.65770422508651, "y": 45.388378571037556, "z": 1.5758646853221379}, "heading": {"w": 0.6629327207389198, "x": -0.6633184137128391, "y": 0.24505744228266935, "z": -0.24591815668032863}}, {"position": {"x": 43.444482259280534, "y": 46.30664354570089, "z": 1.5776975864225713}, "heading": {"w": 0.6622042660247272, "x": -0.6642722777207863, "y": 0.2445541035487234, "z": -0.24580712265467375}}, {"position": {"x": 44.23459684369756, "y": 47.22729963137843, "z": 1.5768335940016907}, "heading": {"w": 0.6623017943828072, "x": -0.6644328178845625, "y": 0.24382050538659375, "z": -0.2458392255689018}}, {"position": {"x": 45.02927066950776, "y": 48.148520663580804, "z": 1.5774279563215443}, "heading": {"w": 0.6629813650866803, "x": -0.6638918781742963, "y": 0.24431893075499683, "z": -0.2449725366581749}}, {"position": {"x": 45.8270140405549, "y": 49.067133072579125, "z": 1.5737913734350508}, "heading": {"w": 0.6644927061731409, "x": -0.6624380993137045, "y": 0.2449061020442602, "z": -0.2442257341105286}}, {"position": {"x": 46.63165908591036, "y": 49.9884798332602, "z": 1.5765569754166002}, "heading": {"w": 0.6661806026020188, "x": -0.6607898551340793, "y": 0.24696949275487978, "z": -0.2420046316025569}}, {"position": {"x": 47.44627437000545, "y": 50.9085744104686, "z": 1.580883190161321}, "heading": {"w": 0.668002568170947, "x": -0.659021264396918, "y": 0.24970922288485004, "z": -0.2389745718605833}}, {"position": {"x": 48.258624909123576, "y": 51.83914362592751, "z": 1.5972065889678835}, "heading": {"w": 0.6683889235689321, "x": -0.6584922672841371, "y": 0.2513922600281199, "z": -0.23758390596863527}}, {"position": {"x": 49.07677668217639, "y": 52.776469326577086, "z": 1.5943681681666906}, "heading": {"w": 0.6680960490460187, "x": -0.6585185466837163, "y": 0.2534108449524701, "z": -0.23618623283997595}}, {"position": {"x": 49.898004129255405, "y": 53.723500449232795, "z": 1.6023049448386426}, "heading": {"w": 0.6664192665478407, "x": -0.6595237669704074, "y": 0.2551954676462617, "z": -0.2361970263737582}}, {"position": {"x": 50.72087134657129, "y": 54.66678563753118, "z": 1.5963887769508542}, "heading": {"w": 0.6653498631053952, "x": -0.6595392588823811, "y": 0.2568948049167315, "z": -0.23732379751155291}}, {"position": {"x": 51.549050250293256, "y": 55.6076025993168, "z": 1.598852410811099}, "heading": {"w": 0.6658960171701243, "x": -0.6579109658995832, "y": 0.2583416719843315, "z": -0.2387367499619211}}, {"position": {"x": 52.38340945064996, "y": 56.545154175945584, "z": 1.5960605704866075}, "heading": {"w": 0.6667875870335362, "x": -0.6560606283313833, "y": 0.25936751913182976, "z": -0.24022334555746933}}, {"position": {"x": 53.23199486630688, "y": 57.4833212881705, "z": 1.5996471106952979}, "heading": {"w": 0.6670815403401034, "x": -0.6547661163637922, "y": 0.26170155148978397, "z": -0.24040767322860074}}, {"position": {"x": 54.091467605427475, "y": 58.42333426577508, "z": 1.6066942923897316}, "heading": {"w": 0.6664991245938839, "x": -0.6542727008650542, "y": 0.2644779405025688, "z": -0.24032804415184558}}, {"position": {"x": 54.94802572226892, "y": 59.37317852495214, "z": 1.612034222606967}, "heading": {"w": 0.6650780745320561, "x": -0.6546591417052665, "y": 0.26548875531920113, "z": -0.24209147807701922}}, {"position": {"x": 55.81362552506302, "y": 60.3182985761506, "z": 1.6148373651927377}, "heading": {"w": 0.6635590300158194, "x": -0.6551312478159815, "y": 0.2673269705199196, "z": -0.2429583352185725}}, {"position": {"x": 56.68451456822873, "y": 61.26810660239239, "z": 1.614490662251863}, "heading": {"w": 0.6618404615346096, "x": -0.6560005843455942, "y": 0.2680727140777542, "z": -0.24447383659786223}}, {"position": {"x": 57.55680670550477, "y": 62.21726638806379, "z": 1.60435242693352}, "heading": {"w": 0.6609536670254297, "x": -0.6561947352455068, "y": 0.268133145790376, "z": -0.24627897922939257}}]



intrinsics.json

> {"fx": 1970.0131, "fy": 1970.0091, "cx": 970.0002, "cy": 483.2988}

**Comment by Leozyc-waseda** [comment]
你的调好的参数可以分享一下给我吗

如果可以的话具体怎么调可以教我一下吗~ ， 我想把左右两边的照片都利用一下 :)

**Comment by cll5854** [comment]
> 看了一下pandaset的文档，应该是点云都转成world坐标系了，相机每帧有world坐标系下的pose，也就是说每帧都用相机pose当外参就行，和内参乘。这个工具最新的版本也支持每帧有单独的外参 需要下面的pose.json和intrinsics.json ├── camera │ ├── back_camera │ │ ├── 00.jpg │ │ . │ │ . │ │ . │ │ ├── 79.jpg │ │ ├── intrinsics.json │ │ ├── poses.json │ │ └── timestamps.json
> 
> 这是我自己大致调了一下的图 ![image](https://user-images.githubusercontent.com/7512334/177585409-63554f5a-6876-4f6c-84d9-18589a3a41fb.png)

每一帧都有外参的样例格式有吗？在项目中没有找到？ @naurril
