### ISSUE TITLE
Radar data

### ISSUE THREAD

**Issue by rgendry** [naurril/SUSTechPOINTS#92]
Hi,
Can you provide any examples of radar data files?
Thanks!

**Comment by naurril** [comment]
radar data is also pcd, the tool supports x,y,z, and vx,vy,vz fileds. v for velocity.


./data/scene-xxx/radar/radar_name/frame_xxx.pcd
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z _ vx vy vz id _
SIZE 4 4 4 1 4 4 4 1 1
TYPE F F F U F F F U U
COUNT 1 1 1 4 1 1 1 1 3
WIDTH 3
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 3
```

calib is needed to visualize radar,
```
./data/scene-xxx/calib/radar/radar-name.json
{
    "rotation":[0,0,3.14159265],  //euler, zxy
    "translation": [0, -2.62, -1.337 ],
    "color":[0.0,1.0,0.0],
    "disable":false,
    "point_size": 4
}

```

**Comment by rgendry** [comment]
Thank you :)

**Comment by KoleMax** [comment]
Hi @naurril !
Can you please show how radar data is drawn on the screen? 
I'm getting just green points without any vectors:(
<img width="487" alt="image" src="https://user-images.githubusercontent.com/48202995/181237627-1278c983-de0b-4e9e-96f9-965f08f63633.png">

**Comment by naurril** [comment]
> Hi @naurril ! Can you please show how radar data is drawn on the screen? I'm getting just green points without any vectors:( 

if everything is ok, there should be a line starting from the green point indicating direction and speed.
like this. 
![image](https://user-images.githubusercontent.com/7512334/181277432-89dcb51e-3b72-4d83-8b96-94685e88a1c8.png)

which branch are you using? some may have bugs showing radar points

**Comment by KoleMax** [comment]
I'm using dev-auto-annotate.
Fixed this problem, this was because i was using ascii encoding instead of binary in pcd:)
And why PCDLoader doesn't support velocity fields in pcd in ascii encoding?

**Comment by naurril** [comment]
sorry forgot the the ascii/binary_compressed format. thanks for pointing it out! I will add them later.

**Comment by KoleMax** [comment]
@naurril, I can make a PR to dev-autoannotate branch with fix if you want

**Comment by naurril** [comment]
> @naurril, I can make a PR to dev-autoannotate branch with fix if you want

yes，please， thank you！

**Comment by KoleMax** [comment]
@naurril can you please give permission to push a branch with fix?

**Comment by KoleMax** [comment]
Oh, sorry, forgot about the fork, here https://github.com/naurril/SUSTechPOINTS/pull/95

**Comment by naurril** [comment]
merged, thank you!
