### ISSUE TITLE
无法通过右键点击“New"新增bbox

### ISSUE THREAD

**Issue by Yaozh66** [naurril/SUSTechPOINTS#98]
你好！
非常感谢贡献了一个这么棒的项目。我在主界面里面在一个点处右键然后将鼠标移至New选项，但并没有显示副菜单，无法通过该方式生成新的bbox，就像下面图片显示一样，想咨询一下你的建议。
谢谢！
![2022-08-31 10-58-54 的屏幕截图](https://user-images.githubusercontent.com/44368323/187583326-558036e3-f03f-4d95-9b22-f976338ac941.png)

**Comment by naurril** [comment]
用的什么分支，是不是改了obj_cfg.js了？

**Comment by Yaozh66** [comment]
我使用的是默认的dev-auto-annotate分支，系统是ubuntu20.04，我并没有修改过任何源码，而且我试过右键其他选项是可以工作的，就唯独这个New选项不正常

**Comment by naurril** [comment]
那你打开前端的调试工具(F12)，看看控制台有没有什么报错

**Comment by Yaozh66** [comment]
这是右键并把鼠标放在New之后，在浏览器中F12的控制台输出，好像没有报错（我们并不了解前端的开发(ε(┬┬﹏┬┬))
![2022-08-31 14-16-25屏幕截图](https://user-images.githubusercontent.com/44368323/187607684-c3f4dc5f-ea6a-4340-b242-261ef64ecd96.png)

**Comment by naurril** [comment]
这也没有报什么错．你看看前面还有没有红色错误信息．如果没有的话你用chrome试试

**Comment by Yaozh66** [comment]
哦，在前面确实有一个红色的错误信息，如图：
![2022-08-31 14-34-14屏幕截图](https://user-images.githubusercontent.com/44368323/187609779-6700b525-cf6b-491c-8495-fc42f95df6e4.png)

**Comment by Yaozh66** [comment]
感谢你的建议，我用Chrome浏览器后解决了该问题。Thanks very much!
