### ISSUE TITLE
A Few Questions About the Code

### ISSUE THREAD

**Issue by Yaozh66** [naurril/SUSTechPOINTS#99]
Hello, we are confused about some questions when reading you code:
1. What are the differences or relationships among the variables in your code: "obj_id", "obj_track_id", "obj_local_id“ and ”lock_obj_track_id“ ? 
2. I think the ObjectIdManager in obj_id_list.js should be modified when deleting or altering the id and category of a bbox.
Besides, we are using dev-auto-annotation branch. Can you give us some advice? Thank you.

**Comment by naurril** [comment]
1.
obj_id == obj_track_id, user can modify it or leave it empty
obj_local_id is used internally and can't be changed by user.
lock_obj_track_id is used to select the same object when navigating to prev/next frame.

2. deleting a used obj-id is tricky. you need to make sure the id is really deleted in all frames of the scene.  think about it when a scene contains many frames and only a part of them is loaded.

**Comment by Yaozh66** [comment]
Get it! And one more question, what's the use of the red little circle in the center right bottom of this side-view of z-axis? 
![2022-09-09 09-37-16屏幕截图](https://user-images.githubusercontent.com/44368323/189254284-f21ba2bf-b187-41a3-9a87-583ea485104b.png)

**Comment by naurril** [comment]
The red circle indicates the direction of original point (0,0,0) (or ego car), maybe a  cross is better.

**Comment by Yaozh66** [comment]
Thanks very much! You solved my question!
